const fs = require('node:fs');
const path = require('node:path');
const esbuild = require('esbuild');

const root = path.resolve(__dirname, '..');
const assetDir = path.join(root, 'assets/atlas');
const regions = require('../src/features/region/atlasRegions.json');
const dataUrl = (file, mime) => `data:${mime};base64,${fs.readFileSync(file).toString('base64')}`;

async function buildAtlas() {
  const assets = {
    land: JSON.parse(fs.readFileSync(path.join(assetDir, 'world-land.json'), 'utf8')),
    font: dataUrl(path.join(root, 'node_modules/@expo-google-fonts/assistant/700Bold/Assistant_700Bold.ttf'), 'font/ttf'),
    photos: Object.fromEntries(regions.map(({ id }) => [id, dataUrl(path.join(assetDir, `${id}-thumb.webp`), 'image/webp')])),
  };
  const result = await esbuild.build({
    absWorkingDir: root, entryPoints: ['src/features/region/globe/runtime.js'],
    bundle: true, write: false, minify: true, format: 'iife', platform: 'browser', target: 'es2020',
    define: { __ATLAS_ASSETS__: JSON.stringify(assets) }, legalComments: 'inline',
  });
  const script = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
  const html = `<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; font-src data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'none'; base-uri 'none'; form-action 'none'"><style>*{box-sizing:border-box}html,body,main{margin:0;width:100%;height:100%;overflow:hidden;background:#0a2238}main{position:relative;touch-action:none}canvas{position:absolute;inset:0;width:100%;height:100%;cursor:grab}.photos{pointer-events:none}.marker{position:absolute;transform:translate(-50%,-50%);border:0;border-radius:12px;background:transparent;min-width:44px;min-height:44px;padding:0;cursor:pointer}button:focus-visible,canvas:focus-visible{outline:3px solid #ffb34d;outline-offset:2px}</style></head><body><main><canvas tabindex="0" role="img" aria-label="גלובוס אינטראקטיבי. גררו לסיבוב או בחרו אזור בכפתורים."></canvas></main><script>window.__ATLAS_CHANNEL__=__CHANNEL_JSON__;</script><script>${script}</script></body></html>`;
  const output = '// Generated by npm run build:atlas. Edit globe/runtime.js and rebuild.\n'
    + 'const document = ' + JSON.stringify(html) + ';\n'
    + 'export function createAtlasDocument(channel) { return document.replace("__CHANNEL_JSON__", JSON.stringify(channel)); }\n';
  const target = path.join(root, 'src/features/region/globe/document.generated.js');
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) throw new Error('Atlas bundle is stale. Run npm run build:atlas.');
  } else fs.writeFileSync(target, output);
  console.log(`Atlas document ${process.argv.includes('--check') ? 'verified' : 'built'} (${Math.round(Buffer.byteLength(output) / 1024)} KB, no remote dependencies).`);
}
buildAtlas().catch((error) => { console.error(error.message); process.exitCode = 1; });
