import { StyleSheet } from 'react-native';

import { colors, fontFamilies, layout, radii, shadows, spacing } from '../../../styles';

export const notificationCenterStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.appSurface,
  },
  content: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    flex: 1,
  },
  header: {
    minHeight: 62,
    paddingHorizontal: 10,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceElevated,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.divider,
  },
  headerSide: {
    minWidth: 88,
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  headerSideLeft: {
    justifyContent: 'flex-end',
  },
  headerTitleWrap: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamilies.semiBold,
    fontSize: 22,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  headerSubtitle: {
    marginTop: 1,
    color: colors.textSecondary,
    fontFamily: fontFamilies.regular,
    fontSize: 12,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  iconButton: {
    width: layout.touchTarget,
    height: layout.touchTarget,
    borderRadius: layout.touchTarget / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  controls: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    backgroundColor: colors.surfaceElevated,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.divider,
    gap: spacing.sm,
  },
  channelTabs: {
    alignSelf: 'stretch',
  },
  summaryRow: {
    minHeight: layout.touchTarget,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryText: {
    color: colors.textSecondary,
    fontFamily: fontFamilies.medium,
    fontSize: 13,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  chipScroller: {
    marginHorizontal: -spacing.lg,
  },
  chipContent: {
    paddingHorizontal: spacing.lg,
    flexDirection: 'row-reverse',
    gap: spacing.sm,
  },
  chip: {
    minHeight: layout.touchTarget,
    paddingHorizontal: spacing.lg,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceElevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipActive: {
    backgroundColor: colors.brand,
    borderColor: colors.brand,
  },
  chipText: {
    color: colors.textSecondary,
    fontFamily: fontFamilies.medium,
    fontSize: 14,
    writingDirection: 'rtl',
  },
  chipTextActive: {
    color: colors.white,
  },
  listContent: {
    paddingVertical: spacing.sm,
  },
  listContentEmpty: {
    flexGrow: 1,
  },
  row: {
    marginHorizontal: 0,
    marginVertical: 0,
    paddingVertical: spacing.md,
    paddingStart: spacing.lg,
    paddingEnd: spacing.md,
    borderRadius: 0,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surfaceElevated,
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  rowUnread: {
    backgroundColor: colors.surfaceElevated,
    borderRightWidth: 3,
    borderRightColor: colors.accentAction,
  },
  rowMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  rowPressed: {
    opacity: 0.78,
  },
  actorColumn: {
    width: 66,
    minHeight: 50,
    alignItems: 'center',
    position: 'relative',
  },
  typeBadge: {
    position: 'absolute',
    bottom: -1,
    left: 0,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brand,
  },
  typeBadgeLike: { backgroundColor: colors.error },
  typeBadgeComment: { backgroundColor: colors.info },
  typeBadgeSystem: { backgroundColor: colors.brand },
  typeBadgeAdmin: { backgroundColor: colors.accentAction },
  typeBadgeUrgent: { backgroundColor: colors.error },
  actorStack: {
    width: 66,
    minHeight: 42,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  actorStackItem: {
    marginStart: -13,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.white,
  },
  rowBody: {
    flex: 1,
    minWidth: 0,
  },
  rowMessage: {
    color: colors.textPrimary,
    fontFamily: fontFamilies.semiBold,
    fontSize: 15,
    lineHeight: 21,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  rowDetail: {
    marginTop: 3,
    color: colors.textSecondary,
    fontFamily: fontFamilies.regular,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  rowMeta: {
    marginTop: 6,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.sm,
  },
  rowTime: {
    color: colors.textMuted,
    fontFamily: fontFamilies.regular,
    fontSize: 12,
    writingDirection: 'rtl',
  },
  unreadPill: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: radii.pill,
    backgroundColor: colors.secondaryLight,
  },
  unreadPillText: {
    color: '#9A5B05',
    fontFamily: fontFamilies.semiBold,
    fontSize: 11,
    writingDirection: 'rtl',
  },
  previews: {
    marginTop: spacing.sm,
    flexDirection: 'row-reverse',
    gap: 6,
  },
  previewImage: {
    flex: 1,
    maxWidth: 58,
    aspectRatio: 1,
    borderRadius: radii.sm,
    backgroundColor: colors.surfaceSubtle,
  },
  rowMenu: {
    width: layout.touchTarget,
    height: layout.touchTarget,
    borderRadius: layout.touchTarget / 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -5,
  },
  centeredState: {
    flex: 1,
    minHeight: 260,
    padding: spacing.xxl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stateTitle: {
    marginTop: spacing.md,
    color: colors.textPrimary,
    fontFamily: fontFamilies.semiBold,
    fontSize: 19,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  stateMessage: {
    maxWidth: 360,
    marginTop: spacing.xs,
    color: colors.textSecondary,
    fontFamily: fontFamilies.regular,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  primaryButton: {
    minHeight: layout.touchTarget,
    marginTop: spacing.lg,
    paddingHorizontal: spacing.xl,
    borderRadius: radii.pill,
    backgroundColor: colors.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonDisabled: { opacity: 0.45 },
  primaryButtonText: {
    color: colors.white,
    fontFamily: fontFamilies.semiBold,
    fontSize: 15,
    writingDirection: 'rtl',
  },
  inlineBanner: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    minHeight: layout.touchTarget,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: colors.errorLight,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.sm,
  },
  inlineBannerText: {
    flex: 1,
    color: '#991B1B',
    fontFamily: fontFamilies.medium,
    fontSize: 13,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  footer: {
    minHeight: 62,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
    justifyContent: 'flex-end',
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheet: {
    width: '100%',
    maxWidth: 620,
    alignSelf: 'center',
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxl,
    paddingHorizontal: spacing.lg,
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    backgroundColor: colors.surfaceElevated,
    ...shadows.large,
  },
  sheetHandle: {
    width: 44,
    height: 4,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: spacing.sm,
    backgroundColor: colors.border,
  },
  sheetTitle: {
    marginVertical: spacing.sm,
    color: colors.textPrimary,
    fontFamily: fontFamilies.semiBold,
    fontSize: 19,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  sheetMessage: {
    color: colors.textSecondary,
    fontFamily: fontFamilies.regular,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  sheetAction: {
    minHeight: 52,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.md,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.md,
  },
  sheetActionPressed: { backgroundColor: colors.surfaceSubtle },
  sheetActionText: {
    flex: 1,
    color: colors.textPrimary,
    fontFamily: fontFamilies.medium,
    fontSize: 16,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  destructiveText: { color: colors.error },
  closeButton: {
    minHeight: layout.touchTarget,
    marginTop: spacing.lg,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    color: colors.brand,
    fontFamily: fontFamilies.semiBold,
    fontSize: 15,
  },
});

export const notificationSettingsStyles = StyleSheet.create({
  scrollContent: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    padding: spacing.lg,
    paddingBottom: spacing.xxxl,
  },
  intro: {
    marginBottom: spacing.lg,
    color: colors.textSecondary,
    fontFamily: fontFamilies.regular,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  section: {
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.surfaceElevated,
    ...shadows.small,
  },
  sectionTitle: {
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    color: colors.textPrimary,
    fontFamily: fontFamilies.semiBold,
    fontSize: 17,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  preferenceRow: {
    minHeight: 62,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.divider,
  },
  preferenceRowLast: { borderBottomWidth: 0 },
  preferenceCopy: { flex: 1 },
  preferenceLabel: {
    color: colors.textPrimary,
    fontFamily: fontFamilies.medium,
    fontSize: 15,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  preferenceHint: {
    marginTop: 2,
    color: colors.textMuted,
    fontFamily: fontFamilies.regular,
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  saveButton: {
    minHeight: 50,
    borderRadius: radii.pill,
    backgroundColor: colors.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  savedText: {
    marginTop: spacing.md,
    color: colors.success,
    fontFamily: fontFamilies.medium,
    fontSize: 14,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
});
