import { fontFamilies } from "../../../styles/typography";
import { Platform, StyleSheet } from 'react-native';

import { colors } from '../../../styles';

export const recommendationDetailStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.appSurface,
  },
  contentContainer: {
    paddingBottom: 120,
  },
  contentSurface: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    marginTop: -28,
    paddingTop: 30,
    paddingHorizontal: 20,
    paddingBottom: 34,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: colors.white,
  },
  categoryRow: {
    minHeight: 30,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 7,
  },
  categoryText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  title: {
    marginTop: 8,
    color: colors.textPrimary,
    fontSize: 29,
    lineHeight: 36,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  locationStack: {
    marginTop: 10,
    gap: 6,
  },
  locationRow: {
    minHeight: 44,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 7,
  },
  locationText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 21,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  placeText: {
    color: colors.textPrimary,
    fontFamily: fontFamilies.medium,
  },
  authorRow: {
    marginTop: 14,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.divider,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  authorButton: {
    minHeight: 48,
    flex: 1,
    minWidth: 0,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 11,
  },
  authorCopy: {
    flex: 1,
    minWidth: 0,
  },
  authorName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  authorDate: {
    marginTop: 3,
    color: colors.textMuted,
    fontSize: 12,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  editButton: {
    minWidth: 78,
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#F8FAFC',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  editText: {
    color: colors.primary,
    fontSize: 13,
    fontFamily: fontFamilies.semiBold,
    writingDirection: 'rtl',
  },
  section: {
    marginTop: 26,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 19,
    lineHeight: 25,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  body: {
    marginTop: 9,
    color: colors.textSecondary,
    fontSize: 16,
    lineHeight: 26,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  factsGrid: {
    marginTop: 13,
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    columnGap: 14,
    rowGap: 4,
  },
  factItem: {
    width: '47%',
  },
  factItemFull: {
    width: '100%',
  },
  metadataLine: {
    marginTop: 12,
  },
  extraGroup: {
    marginTop: 15,
  },
  extraTitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  extraMetadataLine: {
    marginTop: 6,
  },
  needsList: {
    marginTop: 9,
  },
  needRow: {
    minHeight: 50,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  needIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surfaceSubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  needText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 14,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  stickyBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 8,
    paddingHorizontal: 18,
    backgroundColor: Platform.OS === 'web' ? 'rgba(255,255,255,0.98)' : 'rgba(255,255,255,0.96)',
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 10,
  },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 12,
  },
  loadingText: {
    color: colors.textSecondary,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
});
