export const LOCATION_COPY = Object.freeze({
  he: Object.freeze({
    exactLocationLabel: 'מיקום מדויק',
    exactLocationPlaceholder: 'חפש מקום / אטרקציה / מסעדה...',
    exactLocationHelper: 'חפשו ובחרו תוצאה כדי שנוכל לשייך את ההמלצה לעיר הנכונה',
    search: 'חיפוש',
    searchLocation: 'חיפוש מיקום',
    searchGoogle: 'חפש ב-Google',
    loading: 'טוען...',
    resolving: 'טוען פרטי מיקום...',
    noResults: 'לא נמצאו תוצאות',
    retry: 'נסו שוב',
    chooseAnother: 'בחירת תוצאה אחרת',
    chooseAnotherSearchResult: 'בחירת תוצאת חיפוש אחרת',
    destinationChoiceHeading: 'לאיזה יעד לשייך את המקום?',
    destinationChoiceHelper: 'מצאנו כמה יעדים מתאימים. הבחירה לא מפעילה חיפוש נוסף.',
    confirmLocation: 'אישור המיקום',
    mapPreview: 'תצוגה מקדימה של המיקום',
    mapUnavailable: 'לא הצלחנו להציג את המפה. אפשר עדיין לאשר את המיקום.',
    supportCode: 'קוד תמיכה',
    errors: Object.freeze({
      dailyQuota: 'מגבלת המיקום היומית הושגה. אפשר לנסות שוב לאחר האיפוס מחר.',
      temporaryQuota: 'מגבלת החיפוש הזמנית הושגה. נסו שוב בעוד זמן קצר.',
      requestCeiling: 'לא הצלחנו לאמת את המקום במסגרת החיפוש הזה. בחרו תוצאה מדויקת יותר.',
      timeout: 'טעינת המקום נמשכה זמן רב מדי. נסו שוב.',
      expired: 'החיפוש פג תוקף. חפשו ובחרו את המקום מחדש.',
      destinationRequired: 'המקום נמצא, אבל נדרשת בחירת עיר או אזור מתאימים.',
      placeNotFound: 'המקום שנבחר כבר לא זמין. חפשו ובחרו תוצאה אחרת.',
      destinationNotFound: 'היעד שנבחר כבר לא זמין. חפשו ובחרו עיר או אזור מחדש.',
      invalidSelection: 'המקום והיעד אינם תואמים. בחרו יעד קרוב ומתאים יותר.',
      ambiguous: 'לא ניתן לזהות יעד יחיד בבטחה. בחרו מקום מדויק יותר.',
      network: 'לא הצלחנו להתחבר לשירות המקומות. בדקו את החיבור ונסו שוב.',
      temporarilyLocked: 'היעד מתעדכן כעת. הבחירה נשמרה ואפשר לנסות שוב בעוד רגע.',
      support: 'לא הצלחנו להשלים את אימות המקום. בחרו תוצאה אחרת, ואם הבעיה נמשכת פנו לתמיכה עם קוד התמיכה.',
      unknown: 'לא הצלחנו לטעון את המקום. נסו שוב או בחרו תוצאה אחרת.',
    }),
  }),
  en: Object.freeze({
    exactLocationLabel: 'Exact location',
    exactLocationPlaceholder: 'Search for a place, attraction, or restaurant...',
    exactLocationHelper: 'Search and select a result so we can assign the recommendation to the correct destination.',
    search: 'Search',
    searchLocation: 'Search locations',
    searchGoogle: 'Search Google',
    loading: 'Loading...',
    resolving: 'Loading location details...',
    noResults: 'No results found',
    retry: 'Try again',
    chooseAnother: 'Choose another result',
    chooseAnotherSearchResult: 'Choose another search result',
    destinationChoiceHeading: 'Which destination should contain this place?',
    destinationChoiceHelper: 'We found several matches. Choosing one will not run another search.',
    confirmLocation: 'Confirm location',
    mapPreview: 'Location preview',
    mapUnavailable: 'We could not display the map. You can still confirm this location.',
    supportCode: 'Support code',
    errors: Object.freeze({
      dailyQuota: 'Your daily location limit has been reached. Try again after the reset tomorrow.',
      temporaryQuota: 'The temporary search limit has been reached. Try again shortly.',
      requestCeiling: 'We could not verify this place within this search. Choose a more specific result.',
      timeout: 'The location took too long to load. Try again.',
      expired: 'This search expired. Search for and select the place again.',
      destinationRequired: 'The place was found, but you need to choose its city or region.',
      placeNotFound: 'The selected place is no longer available. Search for and choose another result.',
      destinationNotFound: 'The selected destination is no longer available. Search for and choose a city or region again.',
      invalidSelection: 'The place and destination do not match. Choose a closer destination.',
      ambiguous: 'We could not identify one destination safely. Choose a more specific place.',
      network: 'We could not connect to the location service. Check your connection and try again.',
      temporarilyLocked: 'This destination is being updated. Your selection is saved; try again shortly.',
      support: 'We could not complete location verification. Choose another result, or contact support with the support code if it continues.',
      unknown: 'We could not load the location. Try again or choose another result.',
    }),
  }),
});

export function locationCopy(locale = 'he') {
  return LOCATION_COPY[String(locale || '').toLowerCase() === 'en' ? 'en' : 'he'];
}
