import { StyleSheet } from 'react-native';
import { fontFamilies as fonts } from '../../../styles/typography';
import { communityPalette as c } from '../../../styles/communityDiscovery';
import { getTabOverlayBottomInset } from '../../../navigation/tabBarLayout';

const rtl = { textAlign: 'right', writingDirection: 'rtl' };
const row = { direction: 'ltr', flexDirection: 'row-reverse', alignItems: 'center', gap: 8 };
const label = { ...rtl, color: c.navy, fontFamily: fonts.semiBold, fontSize: 14, lineHeight: 20 };
export function createDestinationStyles(width = 390, insets = {}) {
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: c.sand },
    content: { paddingBottom: getTabOverlayBottomInset(insets) + 16, alignSelf: 'center', width: '100%', maxWidth: 720 },
    hero: { minHeight: Math.max(212, 168 + (insets.top || 0)), overflow: 'hidden', backgroundColor: c.navy },
    heroBackground: { ...StyleSheet.absoluteFill, direction: 'ltr' },
    heroContent: { minHeight: Math.max(212, 168 + (insets.top || 0)), paddingTop: (insets.top || 0) + 8, paddingHorizontal: 16, paddingBottom: 20, justifyContent: 'space-between' },
    heroImage: { ...StyleSheet.absoluteFill },
    heroShade: { ...StyleSheet.absoluteFill },
    heroActions: { ...row, justifyContent: 'space-between', marginBottom: 20 },
    actionButton: { width: 44, height: 44, borderRadius: 22, padding: 0, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center' },
    heroCopy: { gap: 4 },
    heroCredit: { position: 'relative', bottom: 0, marginTop: 8 },
    cityName: { ...rtl, color: c.white, fontSize: 32, lineHeight: 38, fontFamily: fonts.bold },
    countryName: { ...rtl, color: c.white, fontSize: 14, lineHeight: 20 },
    sections: { padding: 16, gap: 16 },
    section: { gap: 8 },
    sectionTitle: { ...rtl, fontSize: 18, lineHeight: 24, fontFamily: fonts.bold, color: c.navy },
    communityTitle: { ...rtl, fontSize: 21, lineHeight: 28, fontFamily: fonts.bold, color: c.navy },
    description: { ...rtl, fontSize: 14, lineHeight: 20, color: c.muted },
    quickGrid: { ...row, alignItems: 'stretch', gap: 8 },
    quickCard: { ...row, flex: 1, minWidth: 0, borderRadius: 10, padding: 12, backgroundColor: c.softBlue },
    weatherCard: { backgroundColor: c.softOrange },
    factCopy: { flex: 1, minWidth: 0 },
    factTitle: { ...rtl, color: c.muted, fontSize: 12, lineHeight: 16, fontFamily: fonts.semiBold },
    factValue: { ...rtl, color: c.navy, fontSize: 16, lineHeight: 22, fontFamily: fonts.semiBold },
    weatherValue: { fontFamily: fonts.bold, fontSize: 20, lineHeight: 26 },
    factDetail: { ...rtl, color: c.muted, fontSize: 12, lineHeight: 16 },
    ltrValue: { writingDirection: 'ltr', textAlign: 'right' },
    neutralCard: { padding: 12, borderRadius: 20, backgroundColor: c.white, gap: 8 },
    essentialsGrid: { ...row, alignItems: 'flex-start', gap: 12 },
    essentialItem: { ...row, flex: 1, minWidth: 0 },
    essentialValue: { ...rtl, color: c.navy, fontSize: 14, lineHeight: 20 },
    airportRow: { ...row, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#E4E4DF', paddingTop: 8 },
    sourcesButton: { ...row, minHeight: 44, justifyContent: 'center' },
    sourcesButtonText: label,
    sourcesList: { padding: 12, borderRadius: 12, backgroundColor: c.white },
    sourceRow: { ...row, minHeight: 44, justifyContent: 'space-between' },
    sourceLabel: { ...label, fontSize: 12 },
    sourceValue: { ...rtl, flex: 1, minWidth: 0, color: c.muted, fontSize: 12, lineHeight: 18 },
    reportRow: { ...row, minHeight: 44, justifyContent: 'flex-start' },
    searchRow: row,
    searchField: { ...row, flex: 1, minWidth: 0, backgroundColor: c.white, borderRadius: 10, paddingHorizontal: 8 },
    searchInput: { ...rtl, flex: 1, minWidth: 0, minHeight: 44, padding: 0, color: c.ink, fontSize: 16, fontFamily: fonts.regular },
    iconButton: { width: 44, height: 44, borderRadius: 10, backgroundColor: c.white, alignItems: 'center', justifyContent: 'center' },
    modes: { ...row, padding: 4, gap: 4, borderRadius: 10, backgroundColor: c.softBlue },
    mode: { ...row, flex: 1, minWidth: 0, minHeight: 44, justifyContent: 'center', borderRadius: 10, padding: 8 },
    modeSelected: { backgroundColor: c.navy },
    modeText: { ...label, flexShrink: 1, fontSize: 16, lineHeight: 22 },
    modeTextSelected: { color: c.white },
    filterSummary: { ...row, justifyContent: 'space-between' },
    filterSummaryLabel: { flex: 1, minWidth: 0 },
    clearButton: { minHeight: 44, justifyContent: 'center' },
    filterBadge: { position: 'absolute', right: -3, top: -3, minWidth: 18, height: 18, borderRadius: 9, backgroundColor: c.orange, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 },
    badgeText: { fontSize: 11, color: c.navy, fontFamily: fonts.bold },
    listItem: { paddingHorizontal: 16 },
    footer: { paddingHorizontal: 16, gap: 12 },
    showMoreButton: { ...row, minHeight: 44, justifyContent: 'center', borderRadius: 10, paddingHorizontal: 12, backgroundColor: c.softBlue },
    showMoreText: label,
    mapCategorySelected: { backgroundColor: c.navy },
    mapCategoryTextSelected: { color: c.white },
    state: { padding: 20, minHeight: 160, gap: 10, alignItems: 'center', justifyContent: 'center', borderRadius: 20, backgroundColor: c.softBlue },
    stateTitle: { ...rtl, color: c.navy, fontSize: 18, lineHeight: 24, fontFamily: fonts.bold, textAlign: 'center' },
    stateText: { ...rtl, color: c.muted, fontSize: 14, lineHeight: 20, textAlign: 'center' },
    loading: { flex: 1, padding: 24, gap: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: c.sand },
    errorText: { ...rtl, fontSize: 16, lineHeight: 22, color: c.navy, textAlign: 'center' },
    mapFrame: { height: 220, width: '100%', borderRadius: 20, overflow: 'hidden', backgroundColor: c.softBlue },
    mapCanvas: { ...StyleSheet.absoluteFill },
    mapExpand: { position: 'absolute', top: 12, left: 12, width: 44, height: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: c.white, elevation: 3, zIndex: 3 },
    mapOverlay: { ...StyleSheet.absoluteFill, backgroundColor: c.softBlue, padding: 20, gap: 8, alignItems: 'center', justifyContent: 'center' },
    mapPill: { position: 'absolute', top: 12, right: 12, maxWidth: '70%', padding: 8, borderRadius: 10, backgroundColor: c.white },
    mapMarker: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, borderWidth: 3, borderColor: c.white, backgroundColor: c.navy },
    mapMarkerSelected: { backgroundColor: c.orange, borderColor: c.navy },
    selectedCard: { backgroundColor: c.white, borderRadius: 20, overflow: 'hidden', paddingTop: 12 },
    selectedRow: { ...row, alignItems: 'flex-start', paddingHorizontal: 12 },
    selectedPhoto: { width: 72, height: 72, borderRadius: 12, backgroundColor: c.softBlue },
    selectedCopy: { flex: 1, minWidth: 0, gap: 4 },
    selectedTitle: { ...rtl, fontSize: 16, lineHeight: 22, fontFamily: fonts.bold, color: c.ink },
    selectedActions: { ...row, justifyContent: 'space-between', paddingHorizontal: 12 },
    mapModal: { flex: 1, backgroundColor: c.sand },
    modalHeader: { ...row, padding: 16 },
    modalHeading: { flex: 1, minWidth: 0, ...label, fontSize: 20, lineHeight: 26 },
    modalMap: { flex: 1, minHeight: 100 },
    modalCard: { flexGrow: 0, maxHeight: '35%', padding: 12 },
    mapSearchArea: { position: 'absolute', bottom: 24, alignSelf: 'center', minHeight: 44, justifyContent: 'center', paddingHorizontal: 16, borderRadius: 22, backgroundColor: c.white },
  });
}
