import { Platform, StyleSheet } from 'react-native';

import { colors } from '../../../styles';

export function createDestinationStyles(width = 390, insets = {}) {
  const viewportWidth = Math.max(Number(width) || 0, 320);
  const wide = viewportWidth >= 820;
  const compact = viewportWidth < 360;
  const horizontal = wide ? 24 : 14;

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.appSurface,
      ...(Platform.OS === 'web' ? { direction: 'rtl' } : {}),
    },
    content: {
      width: '100%',
      alignItems: 'center',
      paddingBottom: (insets.bottom || 0) + 72,
    },
    header: {
      width: '100%',
      maxWidth: '100%',
    },
    hero: {
      width: '100%',
      height: (wide ? 360 : 244) + (insets.top || 0),
      position: 'relative',
      overflow: 'hidden',
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      backgroundColor: '#E7EAF2',
    },
    heroImage: {
      width: '100%',
      height: '100%',
    },
    heroFallback: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#E8ECF3',
    },
    heroShade: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      height: 110,
      backgroundColor: 'rgba(15,23,42,0.12)',
    },
    actionButton: {
      position: 'absolute',
      top: Math.max(14, (insets.top || 0) + 8),
      zIndex: 5,
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.94)',
      borderWidth: 1,
      borderColor: 'rgba(30,58,95,0.08)',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 6,
    },
    backButton: {
      right: 14,
    },
    favoriteButton: {
      left: 14,
      padding: 0,
    },
    summaryCard: {
      width: wide ? 720 : '94%',
      maxWidth: '94%',
      alignSelf: 'center',
      marginTop: -54,
      zIndex: 4,
      paddingHorizontal: wide ? 28 : 20,
      paddingVertical: wide ? 23 : 20,
      borderRadius: 28,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: 'rgba(30,58,95,0.08)',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.1,
      shadowRadius: 24,
      elevation: 7,
    },
    summaryTop: {
      flexDirection: 'row-reverse',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 14,
    },
    summaryText: {
      flex: 1,
      minWidth: 0,
    },
    cityName: {
      color: colors.primary,
      fontSize: wide ? 34 : 30,
      lineHeight: wide ? 41 : 36,
      fontWeight: '600',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    countryName: {
      marginTop: 3,
      color: colors.textSecondary,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '400',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    travelerPill: {
      minHeight: 36,
      paddingHorizontal: 12,
      borderRadius: 18,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      gap: 6,
      backgroundColor: '#F5F7FA',
      borderWidth: 1,
      borderColor: '#E5E9F0',
    },
    travelerText: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '500',
      writingDirection: 'rtl',
    },
    description: {
      marginTop: 13,
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 21,
      fontWeight: '400',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    main: {
      width: Math.min(viewportWidth, 1120),
      maxWidth: '100%',
      marginTop: 22,
      paddingHorizontal: horizontal,
      flexDirection: wide ? 'row-reverse' : 'column',
      alignItems: wide ? 'flex-start' : 'stretch',
      gap: 18,
    },
    overviewColumn: {
      width: wide ? 370 : '100%',
      gap: 16,
    },
    communityColumn: {
      flex: wide ? 1 : undefined,
      width: wide ? undefined : '100%',
      minWidth: 0,
    },
    sectionHeader: {
      marginBottom: 11,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    sectionTitle: {
      flex: 1,
      color: colors.primary,
      fontSize: 21,
      lineHeight: 27,
      fontWeight: '600',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    sectionSubtitle: {
      marginTop: 3,
      color: colors.textLight,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '400',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    quickSection: {
      width: '100%',
    },
    quickGrid: {
      width: '100%',
      flexDirection: 'row-reverse',
      flexWrap: 'wrap',
      gap: 9,
    },
    quickCard: {
      width: compact ? '47%' : '30%',
      flexGrow: 1,
      minWidth: compact ? 130 : 100,
      minHeight: 132,
      paddingHorizontal: 12,
      paddingVertical: 13,
      borderRadius: 20,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: '#E2E7EE',
      alignItems: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.035,
      shadowRadius: 10,
      elevation: 1,
    },
    factIcon: {
      width: 34,
      height: 34,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F1F4F8',
    },
    weatherIcon: {
      backgroundColor: '#FFF8E8',
    },
    factTitle: {
      marginTop: 10,
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: '500',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    factValue: {
      width: '100%',
      marginTop: 4,
      color: colors.textPrimary,
      fontSize: 16,
      lineHeight: 21,
      fontWeight: '600',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    factDetail: {
      width: '100%',
      marginTop: 3,
      color: colors.textLight,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '400',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    neutralCard: {
      width: '100%',
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderRadius: 22,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: '#E2E7EE',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.035,
      shadowRadius: 10,
      elevation: 1,
    },
    essentialRow: {
      minHeight: 58,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      gap: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#EDF0F4',
    },
    essentialRowLast: {
      borderBottomWidth: 0,
    },
    rowIcon: {
      width: 38,
      height: 38,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F1F4F8',
    },
    essentialLabel: {
      flex: 1,
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '500',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    essentialValue: {
      flex: 1.25,
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '500',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    sourcesButton: {
      minHeight: 48,
      marginTop: 3,
      paddingHorizontal: 12,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 16,
      backgroundColor: '#F7F8FA',
    },
    sourcesButtonText: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '500',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    sourcesList: {
      marginTop: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 16,
      backgroundColor: '#F7F8FA',
    },
    sourceRow: {
      minHeight: 36,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    sourceLabel: {
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: '500',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    sourceValue: {
      flex: 1,
      color: colors.textLight,
      fontSize: 10,
      fontWeight: '400',
      textAlign: 'left',
      writingDirection: 'rtl',
    },
    communityHeader: {
      paddingHorizontal: 2,
    },
    filters: {
      marginTop: 13,
      marginBottom: 14,
      flexDirection: 'row-reverse',
      flexWrap: 'wrap',
      gap: 8,
    },
    filter: {
      minHeight: 44,
      paddingHorizontal: 16,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: '#E2E7EE',
    },
    filterActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    filterText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '500',
      writingDirection: 'rtl',
    },
    filterTextActive: {
      color: colors.white,
    },
    recommendationList: {
      gap: 14,
    },
    recommendationPreview: {
      width: '100%',
      minHeight: 112,
      padding: 10,
      borderRadius: 21,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: '#E2E7EE',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.035,
      shadowRadius: 10,
      elevation: 1,
    },
    recommendationImage: {
      width: 92,
      height: 92,
      borderRadius: 16,
      backgroundColor: '#E8ECF3',
    },
    recommendationImageFallback: {
      width: 92,
      height: 92,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F1F4F8',
    },
    recommendationBody: {
      flex: 1,
      minWidth: 0,
      alignItems: 'flex-end',
    },
    recommendationCategory: {
      minHeight: 25,
      paddingHorizontal: 9,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F1F4F8',
    },
    recommendationCategoryText: {
      color: colors.textSecondary,
      fontSize: 10,
      fontWeight: '500',
      writingDirection: 'rtl',
    },
    recommendationTitle: {
      width: '100%',
      marginTop: 6,
      color: colors.textPrimary,
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '600',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    recommendationDescription: {
      width: '100%',
      marginTop: 3,
      color: colors.textLight,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '400',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    recommendationChevron: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F7F8FA',
    },
    showMoreButton: {
      minHeight: 48,
      marginTop: 14,
      borderRadius: 24,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: '#D9E0E8',
    },
    showMoreText: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '600',
      writingDirection: 'rtl',
    },
    emptyState: {
      minHeight: 190,
      paddingHorizontal: 20,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: '#E2E7EE',
    },
    emptyTitle: {
      marginTop: 10,
      color: colors.textPrimary,
      fontSize: 17,
      fontWeight: '600',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    emptyText: {
      marginTop: 5,
      color: colors.textLight,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '400',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    loading: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.appSurface,
    },
    errorText: {
      marginTop: 12,
      color: colors.textSecondary,
      fontSize: 15,
      textAlign: 'center',
      writingDirection: 'rtl',
    },
  });
}
