const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');
const { nativeMetadataBytes, prepareSource, verifySource, createEasRunner } = require('./easReleaseSource');
const { fixture } = require('./testFixtures/easRelease');
const sha1 = b => crypto.createHash('sha1').update(b).digest('hex');

test('only line endings are normalized and a real native metadata edit is rejected', () => {
  const expected = Buffer.from('build metadata\r\n');
  assert.deepEqual(nativeMetadataBytes(Buffer.from('build metadata\n'), sha1(expected), 'metadata'), expected);
  assert.deepEqual(nativeMetadataBytes(expected, sha1(expected), 'metadata'), expected);
  assert.throws(() => nativeMetadataBytes(Buffer.from('changed metadata\n'), sha1(expected), 'metadata'), /content changed/);
  const lf = Buffer.from('build metadata\n');
  assert.deepEqual(nativeMetadataBytes(expected, sha1(lf), 'metadata', 'lf'), lf);
  assert.throws(() => nativeMetadataBytes(Buffer.from('changed metadata\n'), sha1(lf), 'metadata', 'lf'), /content changed/);
  assert.throws(() => nativeMetadataBytes(lf, sha1(lf), 'metadata', 'other'), /Unsupported/);
});
test('a tracked Git archive excludes unrelated root config and detects source tampering', t => {
  const f = fixture(t);
  const git = args => execFileSync('git', args, { cwd: f.root, encoding: 'utf8', windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  git(['init', '-q']);
  git(['config', 'core.autocrlf', 'false']);
  const easPath = path.join(f.root, 'client/eas.json');
  fs.writeFileSync(easPath, fs.readFileSync(easPath, 'utf8').replace(/\r\n/g, '\n'));
  fs.writeFileSync(path.join(f.root, 'client/.gitignore'), 'node_modules/\n');
  fs.writeFileSync(path.join(f.root, 'client/example.txt'), 'unchanged\n');
  git(['add', '--', 'README.md', 'client/app.json', 'client/eas.json', 'client/.gitignore', 'client/example.txt', 'config/eas-ios-native-baseline.json']);
  git(['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.test', 'commit', '-qm', 'fixture']);
  fs.mkdirSync(path.join(f.root, 'client/node_modules'));
  fs.writeFileSync(path.join(f.root, 'client/node_modules/dependency.txt'), 'native dependency bytes');
  fs.writeFileSync(path.join(f.root, 'app.json'), '{"unrelated":true}');
  const baseline = { metadataCrlfSha1: { 'client/.gitignore': sha1(Buffer.from('node_modules/\r\n')) } };
  const source = prepareSource({ repoRoot: f.root, baseline });
  assert.equal(fs.existsSync(path.join(source.sourceRoot, 'app.json')), false);
  assert.equal(fs.readFileSync(path.join(f.root, 'app.json'), 'utf8'), '{"unrelated":true}');
  assert.equal(fs.readFileSync(path.join(source.sourceRoot, 'client/.gitignore'), 'utf8'), 'node_modules/\r\n');
  assert.equal(fs.readFileSync(path.join(source.sourceRoot, 'client/example.txt'), 'utf8'), 'unchanged\r\n');
  assert.equal(verifySource(source).trackedFiles, 6);
  // Exercise the real subprocess environment without contacting EAS. The fake
  // CLI reads only these public values; it is outside the tracked archive.
  const fakeCli = path.join(f.root, 'fake-cli');
  fs.mkdirSync(path.join(fakeCli, 'bin'), { recursive: true });
  fs.writeFileSync(path.join(fakeCli, 'package.json'), JSON.stringify({ version: '22.6.0' }));
  const entry = path.join(fakeCli, 'bin/read-env.js');
  fs.writeFileSync(entry, 'console.log(JSON.stringify({ project: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID, environment: process.env.PLANLI_ENV }));');
  assert.deepEqual(JSON.parse(createEasRunner(source, { entry })([])), { project: 'planli-f0b12', environment: 'production' });
  const lfEas = Buffer.from(fs.readFileSync(path.join(f.root, 'client/eas.json'), 'utf8').replace(/\r\n/g, '\n'));
  const localBaseline = { ...baseline, dependencyLayout: 'local-copy', metadataLfSha1: { 'client/eas.json': sha1(lfEas) } };
  const local = prepareSource({ repoRoot: f.root, baseline: localBaseline });
  const localDependencies = path.join(local.sourceRoot, 'client/node_modules');
  assert.equal(fs.lstatSync(localDependencies).isSymbolicLink(), false);
  assert.equal(fs.readFileSync(path.join(localDependencies, 'dependency.txt'), 'utf8'), 'native dependency bytes');
  fs.writeFileSync(path.join(f.root, 'client/node_modules/dependency.txt'), 'changed checkout dependency');
  assert.equal(fs.readFileSync(path.join(localDependencies, 'dependency.txt'), 'utf8'), 'native dependency bytes');
  assert.deepEqual(fs.readFileSync(path.join(local.sourceRoot, 'client/eas.json')), lfEas);
  assert.equal(verifySource(local).trackedFiles, 6);
  fs.writeFileSync(path.join(local.sourceRoot, 'client/eas.json'), lfEas.toString().replace(/\n/g, '\r\n'));
  assert.throws(() => verifySource(local), /line endings changed/);
  assert.throws(() => prepareSource({ repoRoot: f.root, baseline: { ...baseline, dependencyLayout: 'unknown' } }), /Unsupported/);
  assert.throws(() => prepareSource({ repoRoot: f.root, baseline: { ...localBaseline, metadataLfSha1: baseline.metadataCrlfSha1 } }), /Conflicting/);
  fs.writeFileSync(path.join(source.sourceRoot, 'client/example.txt'), 'changed\n');
  assert.throws(() => verifySource(source), /Archived source mismatch/);
  git(['add', '--', 'app.json']);
  git(['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.test', 'commit', '-qm', 'invalid root config fixture']);
  assert.throws(() => prepareSource({ repoRoot: f.root, baseline }), /must live under client/);
});
