const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const targets = ['client/src/config/publicLinks.generated.js', 'hosting/assets/public-links.generated.js'];
function synchronize({ check = false } = {}) {
  const source = fs.readFileSync(path.join(root, 'functions/publicLinks.js'), 'utf8').replace(/\r\n/g, '\n');
  const expected = '// Generated by scripts/syncPublicLinks.js. Do not edit directly.\n' + source;
  const drift = targets.filter(target => !fs.existsSync(path.join(root, target))
    || fs.readFileSync(path.join(root, target), 'utf8').replace(/\r\n/g, '\n') !== expected);
  if (check && drift.length) throw new Error('Public link contract is stale: ' + drift.join(', '));
  if (!check) for (const target of drift) fs.writeFileSync(path.join(root, target), expected);
  return drift;
}
if (require.main === module) {
  try { synchronize({ check: process.argv.includes('--check') }); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
module.exports = { synchronize };
