const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const policyPath = path.join(root, 'config', 'legal-policy.json');
const clientPath = path.join(root, 'client', 'src', 'constants', 'legalPolicy.generated.js');
const functionsPath = path.join(root, 'functions', 'legalPolicy.generated.js');
const storageRulesPath = path.join(root, 'storage.rules');
const START = '        // BEGIN GENERATED LEGAL POLICY';
const END = '        // END GENERATED LEGAL POLICY';

function loadPolicy() {
  const value = JSON.parse(fs.readFileSync(policyPath, 'utf8'));
  if (!Number.isSafeInteger(value.profileDetailsVersion) || value.profileDetailsVersion < 1) {
    throw new Error('profileDetailsVersion must be a positive integer.');
  }
  for (const name of ['terms', 'privacy']) {
    if (!/^\d{4}-\d{2}-\d{2}-[a-z0-9-]+$/.test(value[name]?.version || '')) {
      throw new Error(`${name}.version is invalid.`);
    }
    if (!String(value[name]?.effectiveDateHe || '').trim()) {
      throw new Error(`${name}.effectiveDateHe is required.`);
    }
  }
  return value;
}

function jsString(value) {
  return JSON.stringify(value);
}

function artifacts(policy) {
  const client = `// Generated by scripts/syncLegalPolicy.js. Do not edit directly.\n` +
    `export const PROFILE_DETAILS_VERSION = ${policy.profileDetailsVersion};\n` +
    `export const TERMS_VERSION = ${jsString(policy.terms.version)};\n` +
    `export const TERMS_EFFECTIVE_DATE_HE = ${jsString(policy.terms.effectiveDateHe)};\n` +
    `export const PRIVACY_VERSION = ${jsString(policy.privacy.version)};\n` +
    `export const PRIVACY_EFFECTIVE_DATE_HE = ${jsString(policy.privacy.effectiveDateHe)};\n`;
  const functions = `// Generated by scripts/syncLegalPolicy.js. Do not edit directly.\n` +
    `module.exports = Object.freeze({\n` +
    `  PROFILE_DETAILS_VERSION: ${policy.profileDetailsVersion},\n` +
    `  TERMS_VERSION: ${jsString(policy.terms.version)},\n` +
    `  TERMS_EFFECTIVE_DATE_HE: ${jsString(policy.terms.effectiveDateHe)},\n` +
    `  PRIVACY_VERSION: ${jsString(policy.privacy.version)},\n` +
    `  PRIVACY_EFFECTIVE_DATE_HE: ${jsString(policy.privacy.effectiveDateHe)},\n` +
    `});\n`;
  const ruleBlock = [
    START,
    `        && user.data.onboarding.profileDetailsVersion == ${policy.profileDetailsVersion}`,
    '        && user.data.onboarding.profileDetailsCompletedAt != null',
    `        && user.data.legal.termsVersion == ${jsString(policy.terms.version).replace(/"/g, "'")}`,
    `        && user.data.legal.privacyVersion == ${jsString(policy.privacy.version).replace(/"/g, "'")}`,
    END,
  ].join('\n');
  return { client, functions, ruleBlock };
}

function replaceRuleBlock(source, block) {
  const start = source.indexOf(START);
  const end = source.indexOf(END);
  if (start < 0 || end < start) throw new Error('Storage Rules legal policy markers are missing.');
  return `${source.slice(0, start)}${block}${source.slice(end + END.length)}`;
}

function synchronize({ check = false } = {}) {
  const expected = artifacts(loadPolicy());
  const currentRules = fs.readFileSync(storageRulesPath, 'utf8');
  const expectedRules = replaceRuleBlock(currentRules, expected.ruleBlock);
  const outputs = [
    [clientPath, expected.client],
    [functionsPath, expected.functions],
    [storageRulesPath, expectedRules],
  ];
  const drift = outputs.filter(([file, content]) => fs.readFileSync(file, 'utf8') !== content);
  if (check && drift.length) {
    throw new Error(`Legal policy artifacts are stale: ${drift.map(([file]) => path.relative(root, file)).join(', ')}`);
  }
  if (!check) drift.forEach(([file, content]) => fs.writeFileSync(file, content));
  return { checked: outputs.length, changed: drift.length };
}

if (require.main === module) {
  try {
    const unknown = process.argv.slice(2).filter((value) => value !== '--check');
    if (unknown.length) throw new Error(`Unknown argument: ${unknown[0]}`);
    const result = synchronize({ check: process.argv.includes('--check') });
    process.stdout.write(`Legal policy synchronized: ${result.checked} artifacts, ${result.changed} changed.\n`);
  } catch (error) {
    process.stderr.write(`Legal policy synchronization failed: ${error.message}\n`);
    process.exitCode = 1;
  }
}

module.exports = { artifacts, loadPolicy, replaceRuleBlock, synchronize };
