import { StyleSheet } from 'react-native';
import { colors, shadows, spacing } from '../styles';

export const guidedFormStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.appSurface,
  },
  scroll: {
    flex: 1,
  },
  content: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
    gap: spacing.md,
  },
  introCard: {
    backgroundColor: colors.primary,
    borderRadius: spacing.radiusXL,
    padding: spacing.xl,
    marginBottom: spacing.xs,
    ...shadows.small,
  },
  eyebrow: {
    color: '#DCE8F6',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  title: {
    color: colors.white,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '800',
    marginTop: spacing.xs,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  intro: {
    color: '#E9F0F8',
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.sm,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  progressTrack: {
    height: 5,
    borderRadius: spacing.radiusFull,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginTop: spacing.lg,
    overflow: 'hidden',
    flexDirection: 'row-reverse',
  },
  progressFill: {
    height: '100%',
    borderRadius: spacing.radiusFull,
    backgroundColor: colors.secondary,
  },
  section: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.radiusLarge,
    overflow: 'hidden',
    ...shadows.small,
  },
  sectionError: {
    borderColor: colors.error,
  },
  sectionComplete: {
    borderColor: '#B8DDCF',
  },
  sectionHeader: {
    minHeight: 76,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.sm,
  },
  sectionCopy: {
    flex: 1,
    alignItems: 'flex-end',
  },
  sectionTitleRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.sm,
  },
  sectionIndex: {
    width: 27,
    height: 27,
    borderRadius: 14,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionIndexComplete: {
    backgroundColor: colors.successLight,
  },
  sectionIndexError: {
    backgroundColor: colors.errorLight,
  },
  sectionIndexText: {
    color: colors.primary,
    fontWeight: '800',
    fontSize: 13,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  sectionSummary: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: spacing.xs,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  sectionSummaryError: {
    color: colors.error,
    fontWeight: '700',
  },
  sectionBody: {
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    padding: spacing.lg,
  },
  continueButton: {
    minHeight: 46,
    borderRadius: spacing.radiusMedium,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  continueText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '800',
    writingDirection: 'rtl',
  },
  footer: {
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    ...shadows.medium,
  },
  footerInner: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
  },
  submitButton: {
    minHeight: 52,
    backgroundColor: colors.primary,
    borderRadius: spacing.radiusMedium,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row-reverse',
    gap: spacing.sm,
  },
  submitButtonDisabled: {
    opacity: 0.55,
  },
  submitText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '800',
    writingDirection: 'rtl',
  },
  fieldGroup: {
    marginBottom: spacing.lg,
  },
  fieldLabel: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: spacing.sm,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  fieldHelper: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: -spacing.xs,
    marginBottom: spacing.sm,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  fieldError: {
    color: colors.error,
    fontSize: 12,
    fontWeight: '600',
    marginTop: spacing.xs,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  choiceRail: {
    writingDirection: 'rtl',
  },
  choiceRailContent: {
    flexDirection: 'row-reverse',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
    paddingHorizontal: 1,
  },
  choiceWrap: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  choiceTile: {
    minWidth: 116,
    minHeight: 66,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.radiusMedium,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  choiceChip: {
    minHeight: 42,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.radiusFull,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceSegment: {
    minHeight: 44,
    flexGrow: 1,
    flexBasis: 120,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.radiusMedium,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  choiceDisabled: {
    opacity: 0.4,
  },
  choiceText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  choiceTextSelected: {
    color: colors.white,
  },
  selectedHint: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: spacing.sm,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  nestedPanel: {
    backgroundColor: colors.background,
    borderRadius: spacing.radiusMedium,
    padding: spacing.md,
    marginTop: spacing.md,
  },
  nestedTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: spacing.sm,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  optionalToggle: {
    minHeight: 46,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    paddingVertical: spacing.md,
    marginTop: spacing.sm,
  },
  optionalToggleText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  checkboxRow: {
    minHeight: 48,
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: spacing.radiusMedium,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    marginTop: spacing.sm,
  },
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.textSecondary,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxBoxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxCheck: {
    color: colors.white,
    fontWeight: '900',
  },
  checkboxText: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
});
