import { Platform, StyleSheet } from 'react-native';

import { colors } from '../../../styles';

export function createProfileStyles(insets = {}, width = 390) {
  const viewportWidth = Math.max(Number(width) || 0, 320);
  const wide = viewportWidth >= 900;
  const tablet = viewportWidth >= 600;
  const horizontal = wide ? 24 : tablet ? 20 : 14;
  const gridWidth = Math.min(viewportWidth, 960);
  const gridTileSize = Math.max(1, (gridWidth - 18) / 3);

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.appSurface,
    },
    listContent: {
      width: '100%',
      alignItems: 'center',
      paddingBottom: (insets.bottom || 0) + 112,
    },
    headerBlock: {
      width: Math.min(viewportWidth, 1120),
      maxWidth: '100%',
      alignSelf: 'center',
      paddingBottom: 12,
    },
    topAction: {
      position: 'absolute',
      top: (insets.top || 0) + 12,
      zIndex: 20,
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.9)',
      borderWidth: 1,
      borderColor: 'rgba(30,58,95,0.08)',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 6,
    },
    topActionStart: {
      left: 16,
    },
    topActionEnd: {
      right: 16,
    },
    heroHeader: {
      width: Math.min(viewportWidth, 1120),
      maxWidth: '100%',
      alignSelf: 'center',
      paddingHorizontal: horizontal,
      paddingTop: 10,
    },
    heroShell: {
      width: '100%',
    },
    heroShellWide: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 16,
    },
    heroMedia: {
      width: '100%',
      height: tablet ? 300 : 222,
      borderRadius: 30,
      overflow: 'hidden',
      backgroundColor: '#E7EAF2',
      position: 'relative',
    },
    heroMediaWide: {
      flex: 1,
      height: 360,
      minWidth: 0,
    },
    heroMediaRow: {
      flex: 1,
      flexDirection: 'row',
      gap: 3,
    },
    heroMediaPrimary: {
      flex: 1.5,
    },
    heroMediaColumn: {
      flex: 1,
      gap: 3,
    },
    heroImage: {
      flex: 1,
      minWidth: 0,
      minHeight: 0,
      backgroundColor: '#DDE3EF',
    },
    heroImageWeb: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      display: 'block',
    },
    heroFallback: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      backgroundColor: colors.primary,
    },
    heroFallbackMap: {
      position: 'absolute',
      width: '130%',
      height: '130%',
      opacity: 0.28,
    },
    heroFallbackIcon: {
      width: 76,
      height: 76,
      borderRadius: 38,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.18)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.38)',
    },
    heroShade: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: '48%',
      backgroundColor: 'rgba(15,23,42,0.18)',
    },
    identityCard: {
      position: 'relative',
      marginHorizontal: 8,
      marginTop: -62,
      paddingTop: 76,
      paddingHorizontal: 18,
      paddingBottom: 18,
      borderRadius: 28,
      alignItems: 'center',
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: 'rgba(30,58,95,0.08)',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.11,
      shadowRadius: 24,
      elevation: 7,
    },
    identityCardWide: {
      width: 360,
      marginHorizontal: 0,
      marginTop: 0,
      paddingTop: 28,
      justifyContent: 'center',
    },
    avatarWrap: {
      position: 'absolute',
      top: -58,
      width: 116,
      height: 116,
      borderRadius: 58,
      padding: 5,
      backgroundColor: colors.white,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.17,
      shadowRadius: 18,
      elevation: 9,
    },
    avatarWrapWide: {
      position: 'relative',
      top: 0,
      marginBottom: 14,
    },
    avatarImage: {
      width: '100%',
      height: '100%',
      borderRadius: 54,
      backgroundColor: colors.accentLight,
    },
    avatarImageWeb: {
      width: '100%',
      height: '100%',
      borderRadius: 54,
      objectFit: 'cover',
      display: 'block',
    },
    avatarPlaceholder: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarInitial: {
      color: colors.primary,
      fontSize: 42,
      fontWeight: '900',
    },
    cameraButton: {
      position: 'absolute',
      right: -2,
      bottom: 2,
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      borderWidth: 3,
      borderColor: colors.white,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 7,
    },
    name: {
      maxWidth: '94%',
      color: colors.textPrimary,
      fontSize: tablet ? 29 : 26,
      lineHeight: tablet ? 35 : 31,
      fontWeight: '900',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    bioRow: {
      maxWidth: '94%',
      marginTop: 8,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    bio: {
      maxWidth: '88%',
      color: colors.textSecondary,
      fontSize: 15,
      lineHeight: 21,
      fontWeight: '600',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    bioPlaceholder: {
      color: colors.textLight,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    editIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F1F5F9',
    },
    statusRow: {
      marginTop: 12,
      flexDirection: 'row-reverse',
      flexWrap: 'wrap',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 7,
    },
    statusPill: {
      minHeight: 34,
      paddingHorizontal: 12,
      borderRadius: 17,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
    },
    statusPillText: {
      fontSize: 12,
      fontWeight: '900',
      writingDirection: 'rtl',
    },
    statsCard: {
      width: '100%',
      marginTop: 16,
      paddingTop: 14,
      borderTopWidth: 1,
      borderTopColor: '#E8ECF3',
      flexDirection: 'row-reverse',
      alignItems: 'stretch',
    },
    statItem: {
      flex: 1,
      minHeight: 68,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    },
    statIconBubble: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F1F5F9',
    },
    statNumber: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: '900',
    },
    statLabel: {
      color: colors.textLight,
      fontSize: 11,
      fontWeight: '800',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    statDivider: {
      width: 1,
      height: '64%',
      alignSelf: 'center',
      backgroundColor: '#E5E7EB',
    },
    statSkeleton: {
      width: 32,
      height: 20,
      borderRadius: 7,
      backgroundColor: '#E8ECF3',
    },
    preferencesSection: {
      marginTop: 14,
      marginHorizontal: 8,
      paddingHorizontal: 16,
      paddingVertical: 18,
      borderRadius: 26,
      backgroundColor: '#FFFCF8',
      borderWidth: 1,
      borderColor: '#F1E7D8',
    },
    preferencesTitleRow: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    preferencesTitle: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    preferencesEdit: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F3EBDD',
    },
    featuredRow: {
      marginTop: 14,
      flexDirection: 'row-reverse',
      gap: 9,
    },
    featuredStamp: {
      flex: 1,
      minHeight: 102,
      paddingHorizontal: 8,
      paddingVertical: 12,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderStyle: 'dashed',
    },
    featuredIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    featuredLabel: {
      color: colors.textPrimary,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '900',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    compactWrap: {
      marginTop: 12,
      flexDirection: 'row-reverse',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      gap: 7,
    },
    compactStamp: {
      minHeight: 34,
      paddingHorizontal: 10,
      borderRadius: 17,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      gap: 5,
      borderWidth: 1,
    },
    compactLabel: {
      maxWidth: 150,
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: '800',
      writingDirection: 'rtl',
    },
    preferenceEmpty: {
      marginTop: 14,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 20,
      backgroundColor: '#F9F1E5',
      alignItems: 'center',
    },
    preferenceEmptyTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    preferenceEmptyText: {
      marginTop: 4,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '600',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    preferenceEmptyButton: {
      marginTop: 10,
      minHeight: 42,
      paddingHorizontal: 16,
      borderRadius: 21,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.primary,
    },
    preferenceEmptyButtonText: {
      color: colors.white,
      fontSize: 12,
      fontWeight: '900',
      writingDirection: 'rtl',
    },
    contentSection: {
      width: gridWidth,
      maxWidth: '100%',
      alignSelf: 'center',
      marginTop: 20,
    },
    contentIntroRow: {
      paddingHorizontal: horizontal,
      flexDirection: 'row-reverse',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
    },
    contentTitle: {
      color: colors.textPrimary,
      fontSize: 23,
      fontWeight: '900',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    contentCount: {
      color: colors.textLight,
      fontSize: 12,
      fontWeight: '800',
      writingDirection: 'rtl',
    },
    contentTabs: {
      marginTop: 13,
      marginHorizontal: horizontal,
      padding: 4,
      borderRadius: 25,
      flexDirection: 'row-reverse',
      backgroundColor: 'rgba(255,255,255,0.86)',
      borderWidth: 1,
      borderColor: 'rgba(30,58,95,0.08)',
    },
    contentTab: {
      flex: 1,
      minHeight: 44,
      borderRadius: 21,
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    contentTabActive: {
      backgroundColor: colors.primary,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.14,
      shadowRadius: 10,
      elevation: 4,
    },
    contentTabText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '900',
      writingDirection: 'rtl',
    },
    contentTabTextActive: {
      color: colors.white,
    },
    contentLoading: {
      paddingVertical: 18,
      alignItems: 'center',
    },
    gridRow: {
      width: gridWidth,
      maxWidth: '100%',
      alignSelf: 'center',
      paddingHorizontal: 3,
      flexDirection: 'row-reverse',
    },
    gridTile: {
      width: gridTileSize,
      maxWidth: gridTileSize,
      flexGrow: 0,
      flexShrink: 0,
      aspectRatio: 1,
      margin: 2,
      overflow: 'hidden',
      position: 'relative',
      backgroundColor: colors.primary,
    },
    gridImage: {
      width: '100%',
      height: '100%',
    },
    gridImageWeb: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      display: 'block',
    },
    gridFallback: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    gridShade: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: '42%',
      backgroundColor: 'rgba(15,23,42,0.18)',
    },
    gridTypeBadge: {
      position: 'absolute',
      top: 8,
      right: 8,
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(15,23,42,0.62)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.45)',
    },
    gridOverlay: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 10,
      paddingVertical: 9,
      backgroundColor: 'rgba(15,23,42,0.76)',
    },
    gridOverlayTitle: {
      color: colors.white,
      fontSize: 12,
      fontWeight: '900',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    gridOverlaySubtitle: {
      marginTop: 2,
      color: 'rgba(255,255,255,0.82)',
      fontSize: 10,
      fontWeight: '700',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    emptyState: {
      marginHorizontal: horizontal,
      marginTop: 18,
      paddingVertical: 34,
      paddingHorizontal: 18,
      borderRadius: 24,
      backgroundColor: colors.white,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(30,58,95,0.08)',
    },
    emptyTitle: {
      marginTop: 10,
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    emptyText: {
      marginTop: 5,
      color: colors.textLight,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '600',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    modalBackdrop: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(15,23,42,0.42)',
    },
    modalCard: {
      width: '100%',
      maxWidth: 620,
      alignSelf: 'center',
      paddingHorizontal: 20,
      paddingTop: 18,
      paddingBottom: (insets.bottom || 0) + 18,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      backgroundColor: colors.white,
    },
    modalHeader: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    modalTitle: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: '900',
      writingDirection: 'rtl',
    },
    modalClose: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F1F5F9',
    },
    modalHelper: {
      marginTop: 7,
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '600',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    bioInput: {
      minHeight: 106,
      marginTop: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: '#CBD5E1',
      color: colors.textPrimary,
      fontSize: 16,
      lineHeight: 23,
      textAlign: 'right',
      writingDirection: 'rtl',
      textAlignVertical: 'top',
      ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
    },
    bioCount: {
      marginTop: 6,
      color: colors.textLight,
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    modalError: {
      marginTop: 8,
      color: colors.error,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    modalActions: {
      marginTop: 14,
      flexDirection: 'row-reverse',
      gap: 9,
    },
    modalButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalButtonSecondary: {
      backgroundColor: '#F1F5F9',
    },
    modalButtonPrimary: {
      backgroundColor: colors.primary,
    },
    modalButtonText: {
      fontSize: 14,
      fontWeight: '900',
      writingDirection: 'rtl',
    },
    modalButtonTextSecondary: {
      color: colors.textSecondary,
    },
    modalButtonTextPrimary: {
      color: colors.white,
    },
  });
}
