import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StatusBar, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import AppText from '../../../components/AppText';
import { colors, tripPlannerStyles as styles } from '../../../styles';
import { createPrivateTrip, deletePrivateTrip, listMyTrips, tripErrorMessage } from '../../../services/TripService';

export default function MyTripsScreen({ navigation }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async ({ refresh = false } = {}) => { refresh ? setRefreshing(true) : setLoading(true); setError(''); try { setItems((await listMyTrips(50)).items || []); } catch (cause) { setError(tripErrorMessage(cause, 'לא הצלחנו לטעון את הטיולים.')); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const create = async () => { try { const result = await createPrivateTrip(); navigation.replace('TripPlanner', { tripId: result.tripId }); } catch (cause) { setError(tripErrorMessage(cause)); } };
  const remove = (trip) => Alert.alert('למחוק את הטיול?', 'הטיול וכל העצירות שבו יימחקו לצמיתות.', [{ text: 'ביטול', style: 'cancel' }, { text: 'מחיקה', style: 'destructive', onPress: async () => { try { await deletePrivateTrip(trip.id); setItems((current) => current.filter((item) => item.id !== trip.id)); } catch (cause) { setError(tripErrorMessage(cause, 'לא הצלחנו למחוק את הטיול.')); } } }]);
  return <SafeAreaView style={styles.fullScreen} edges={['top', 'left', 'right', 'bottom']}><StatusBar barStyle="dark-content" /><View style={styles.pageHeader}><TouchableOpacity style={styles.iconButton} onPress={() => navigation.goBack()} accessibilityLabel="חזרה"><Ionicons name="arrow-forward" size={22} color={colors.primary} /></TouchableOpacity><AppText style={styles.pageHeaderTitle}>הטיולים שלי</AppText><TouchableOpacity style={[styles.iconButton, styles.iconButtonPrimary]} onPress={create} accessibilityLabel="טיול חדש"><Ionicons name="add" size={24} color={colors.primary} /></TouchableOpacity></View><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load({ refresh: true })} />} contentContainerStyle={styles.pageContent}>{!!error && <AppText style={styles.errorText}>{error}</AppText>}{loading && !items.length ? <ActivityIndicator size="large" color={colors.primary} /> : items.map((trip) => <TouchableOpacity key={trip.id} style={styles.tripCard} onPress={() => navigation.navigate('TripPlanner', { tripId: trip.id })} accessibilityRole="button"><View style={styles.tripCardHeader}><View style={styles.tripCardIcon}><Ionicons name="map-outline" size={24} color={colors.primary} /></View><View style={styles.tripCardCopy}><AppText style={styles.tripCardTitle}>{trip.title}</AppText><AppText style={styles.tripCardMeta}>{trip.dayCount} ימים · {trip.stopCount} עצירות{trip.shareActive ? ' · משותף בקישור' : ''}</AppText></View><Ionicons name="chevron-back" size={21} color={colors.primary} /></View><View style={styles.tripCardFooter}><AppText style={styles.tripCardMeta}>נשמר פרטי בחשבון שלך</AppText><TouchableOpacity style={styles.deleteButton} onPress={(event) => { event?.stopPropagation?.(); remove(trip); }} accessibilityLabel={`מחיקת ${trip.title}`}><Ionicons name="trash-outline" size={18} color={colors.error} /></TouchableOpacity></View></TouchableOpacity>)}{!loading && !items.length ? <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="map-outline" size={31} color={colors.accentAction} /></View><AppText style={styles.emptyTitle}>הטיול הבא מתחיל כאן</AppText><AppText style={styles.emptyText}>בנו מסלול חי מהמלצות PlanLi ומהעצירות שלכם.</AppText><TouchableOpacity style={[styles.primaryButton, { marginTop: 18 }]} onPress={create}><AppText style={styles.primaryButtonText}>יצירת הטיול הראשון</AppText></TouchableOpacity></View> : null}</ScrollView></SafeAreaView>;
}
