import { StyleSheet } from 'react-native';
import { colors } from './colors';
import { fontFamilies } from './typography';

const border = '#E4E7EC';
const muted = '#667085';
const ink = '#101828';
const primary = '#3448C5';

export const adminStyles = StyleSheet.create({
  screen: { flex: 1, minHeight: 0, backgroundColor: '#F7F8FA' },
  console: { flex: 1, minHeight: 0, flexDirection: 'row-reverse' },
  consoleMobile: { flexDirection: 'column' },
  sidebar: { width: 244, flexShrink: 0, backgroundColor: '#FFFFFF', borderLeftWidth: 1, borderLeftColor: border, paddingHorizontal: 14, paddingVertical: 20 },
  brandBlock: { flexDirection: 'row-reverse', alignItems: 'center', gap: 11, paddingHorizontal: 8, marginBottom: 26 },
  brandMark: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: primary },
  brandTitle: { fontFamily: fontFamilies.bold, fontSize: 17, color: ink, textAlign: 'right' },
  brandSubtitle: { fontFamily: fontFamilies.regular, fontSize: 12, color: muted, textAlign: 'right', marginTop: 1 },
  sidebarNav: { gap: 5 },
  sidebarItem: { minHeight: 46, borderRadius: 11, flexDirection: 'row-reverse', alignItems: 'center', gap: 11, paddingHorizontal: 12 },
  sidebarItemActive: { backgroundColor: '#EEF0FF' },
  sidebarItemText: { flex: 1, fontFamily: fontFamilies.semiBold, color: '#475467', textAlign: 'right' },
  sidebarItemTextActive: { color: primary },
  sidebarFooter: { marginTop: 'auto', paddingTop: 18, borderTopWidth: 1, borderTopColor: border, flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 7 },
  sidebarFooterText: { flex: 1, fontFamily: fontFamilies.regular, fontSize: 11, lineHeight: 17, color: muted, textAlign: 'right' },
  main: { flex: 1, minWidth: 0, minHeight: 0 },
  topbar: { minHeight: 82, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: border, paddingHorizontal: 18, paddingVertical: 14, flexDirection: 'row-reverse', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  title: { fontFamily: fontFamilies.bold, fontSize: 23, color: ink, textAlign: 'right' },
  subtitle: { fontFamily: fontFamilies.regular, color: muted, textAlign: 'right', marginTop: 3, fontSize: 13 },
  secureBadge: { flexDirection: 'row-reverse', alignItems: 'center', gap: 6, borderRadius: 999, backgroundColor: '#ECFDF3', paddingHorizontal: 10, paddingVertical: 7 },
  secureBadgeText: { fontFamily: fontFamilies.semiBold, color: '#027A48', fontSize: 12 },
  mobileNavScroll: { flexGrow: 0, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: border },
  mobileNav: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 7, paddingHorizontal: 12, paddingVertical: 10 },
  mobileNavItem: { minHeight: 48, flexBasis: '31%', flexGrow: 1, borderRadius: 12, paddingHorizontal: 8, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: '#F2F4F7' },
  mobileNavItemActive: { backgroundColor: primary },
  mobileNavText: { fontFamily: fontFamilies.semiBold, color: '#475467', fontSize: 13 },
  mobileNavTextActive: { color: '#FFFFFF' },
  mainScroll: { flex: 1 },
  mainBody: { flexGrow: 1, width: '100%', maxWidth: 1240, alignSelf: 'center', padding: 22, paddingBottom: 48 },
  mainBodyQueue: { flex: 1, minHeight: 0, padding: 16 },
  sectionHeading: { marginBottom: 18 },
  sectionTitle: { fontFamily: fontFamilies.bold, fontSize: 21, color: ink, textAlign: 'right' },
  sectionDescription: { fontFamily: fontFamilies.regular, fontSize: 14, lineHeight: 21, color: muted, textAlign: 'right', marginTop: 5 },
  subsectionTitle: { fontFamily: fontFamilies.bold, fontSize: 17, color: ink, textAlign: 'right', marginBottom: 8 },
  fieldLabel: { fontFamily: fontFamilies.semiBold, fontSize: 13, color: '#344054', textAlign: 'right', marginTop: 13, marginBottom: 7 },
  helpText: { fontFamily: fontFamilies.regular, fontSize: 12, lineHeight: 18, color: muted, textAlign: 'right', marginTop: 4 },
  contextStrong: { fontFamily: fontFamilies.semiBold, color: '#344054', textAlign: 'right' },
  body: { fontFamily: fontFamilies.regular, color: muted, textAlign: 'right', marginTop: 5, lineHeight: 20 },
  row: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  actions: { flexDirection: 'row-reverse', flexWrap: 'wrap', alignItems: 'center', gap: 8, marginTop: 11 },
  action: { minHeight: 44, borderRadius: 11, paddingHorizontal: 14, flexDirection: 'row-reverse', gap: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEF0FF', borderWidth: 1, borderColor: '#D9DEFF' },
  actionCompact: { minHeight: 38, paddingHorizontal: 11 },
  actionPrimary: { backgroundColor: primary, borderColor: primary },
  actionPrimaryText: { color: '#FFFFFF' },
  actionDisabled: { opacity: 0.5 },
  actionPressed: { opacity: 0.76 },
  actionText: { color: primary, fontFamily: fontFamilies.bold, textAlign: 'center' },
  danger: { backgroundColor: '#FEF3F2', borderColor: '#FECDCA' },
  dangerText: { color: '#B42318' },
  loading: { paddingVertical: 50 },
  empty: { minHeight: 150, paddingVertical: 38, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center' },
  emptyText: { color: muted, fontFamily: fontFamilies.regular, textAlign: 'center', lineHeight: 21 },
  error: { borderRadius: 13, backgroundColor: '#FEF3F2', borderWidth: 1, borderColor: '#FECDCA', padding: 13, marginBottom: 12 },
  errorText: { color: '#B42318', fontFamily: fontFamilies.semiBold, textAlign: 'right', lineHeight: 20 },
  inlineError: { color: '#B42318', fontFamily: fontFamilies.semiBold, textAlign: 'right', marginTop: 10 },
  inlineSuccess: { color: '#027A48', fontFamily: fontFamilies.semiBold, textAlign: 'right', marginTop: 10 },
  stateBlock: { minHeight: 140, alignItems: 'center', justifyContent: 'center', gap: 10 },
  stateText: { color: muted, fontFamily: fontFamilies.regular, textAlign: 'center' },

  metrics: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 12 },
  metric: { flexGrow: 1, flexBasis: 220, minHeight: 154, backgroundColor: '#FFFFFF', borderRadius: 16, padding: 17, borderWidth: 1, borderColor: border },
  metricUrgent: { borderColor: '#FECDCA' },
  metricIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F2F4FF', alignSelf: 'flex-end' },
  metricValue: { fontFamily: fontFamilies.bold, fontSize: 31, color: ink, textAlign: 'right', marginTop: 10 },
  metricLabel: { fontFamily: fontFamilies.semiBold, color: '#344054', textAlign: 'right', marginTop: 2 },
  metricLink: { fontFamily: fontFamilies.semiBold, fontSize: 12, color: primary, textAlign: 'right', marginTop: 12 },
  cardPressed: { opacity: 0.75 },

  queueSection: { flex: 1, minHeight: 0, flexDirection: 'row-reverse', gap: 14 },
  queueListPane: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: border, borderRadius: 16, padding: 14 },
  queueListPaneSplit: { width: 425, flex: 0 },
  viewTabs: { flexDirection: 'row-reverse', gap: 7, paddingBottom: 11 },
  filterChip: { minHeight: 38, borderRadius: 999, borderWidth: 1, borderColor: '#D0D5DD', backgroundColor: '#FFFFFF', paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  filterChipActive: { backgroundColor: primary, borderColor: primary },
  filterChipDanger: { backgroundColor: '#B42318', borderColor: '#B42318' },
  filterChipText: { fontFamily: fontFamilies.semiBold, fontSize: 12, color: '#475467', textAlign: 'center' },
  filterChipTextActive: { color: '#FFFFFF' },
  filterChipDangerText: { color: '#FFFFFF' },
  chipRow: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 7 },
  searchBar: { minHeight: 48, borderWidth: 1, borderColor: '#D0D5DD', borderRadius: 12, backgroundColor: '#FFFFFF', flexDirection: 'row-reverse', alignItems: 'center', gap: 8, paddingHorizontal: 11, marginBottom: 10 },
  searchHero: { minHeight: 60, width: '100%', maxWidth: 920, alignSelf: 'center', borderWidth: 1, borderColor: '#D0D5DD', borderRadius: 15, backgroundColor: '#FFFFFF', flexDirection: 'row-reverse', flexWrap: 'wrap', alignItems: 'center', gap: 9, paddingHorizontal: 13, paddingVertical: 7, marginBottom: 18 },
  searchInput: { flex: 1, minHeight: 44, borderWidth: 0, backgroundColor: 'transparent', paddingHorizontal: 4, textAlign: 'right', writingDirection: 'rtl', fontFamily: fontFamilies.regular, color: ink },
  filtersPanel: { borderRadius: 13, borderWidth: 1, borderColor: border, backgroundColor: '#F9FAFB', padding: 12, marginBottom: 10 },
  input: { minHeight: 46, borderWidth: 1, borderColor: '#D0D5DD', borderRadius: 11, backgroundColor: '#FFFFFF', paddingHorizontal: 12, textAlign: 'right', writingDirection: 'rtl', fontFamily: fontFamilies.regular, color: ink, marginTop: 8 },
  textArea: { minHeight: 76, borderWidth: 1, borderColor: '#D0D5DD', borderRadius: 11, backgroundColor: '#FFFFFF', paddingHorizontal: 12, paddingVertical: 10, textAlign: 'right', textAlignVertical: 'top', writingDirection: 'rtl', fontFamily: fontFamilies.regular, color: ink, marginTop: 9 },
  savedViewEditor: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8, marginTop: 10 },
  savedViewInput: { flex: 1, minHeight: 42, borderWidth: 1, borderColor: '#D0D5DD', borderRadius: 10, backgroundColor: '#FFFFFF', paddingHorizontal: 11, textAlign: 'right', writingDirection: 'rtl', fontFamily: fontFamilies.regular },
  savedView: { minHeight: 38, flexDirection: 'row-reverse', alignItems: 'center', gap: 6, borderRadius: 999, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: border, paddingHorizontal: 10 },
  savedViewText: { fontFamily: fontFamilies.semiBold, fontSize: 12, color: '#475467' },
  bulkBar: { borderRadius: 12, borderWidth: 1, borderColor: '#B2CCFF', backgroundColor: '#EFF8FF', padding: 10, marginBottom: 10 },
  queueRows: { flex: 1, minHeight: 0 },
  queueRowsContent: { paddingBottom: 20 },
  queueRow: { minHeight: 124, flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 10, borderBottomWidth: 1, borderBottomColor: '#EAECF0', paddingVertical: 13, paddingHorizontal: 7 },
  queueRowActive: { backgroundColor: '#F4F5FF', borderRadius: 11 },
  checkbox: { width: 24, height: 24, flexShrink: 0, marginTop: 2, borderWidth: 1.5, borderColor: '#98A2B3', borderRadius: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  checkboxSelected: { backgroundColor: primary, borderColor: primary },
  queueRowContent: { flex: 1, minWidth: 0 },
  queueTitle: { flex: 1, fontFamily: fontFamilies.bold, fontSize: 15, color: ink, textAlign: 'right' },
  queueMeta: { fontFamily: fontFamilies.regular, fontSize: 12, color: muted, textAlign: 'right', marginTop: 5 },
  queueReasons: { fontFamily: fontFamilies.semiBold, fontSize: 12, color: '#344054', textAlign: 'right', marginTop: 7 },
  queueFoot: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  queueFootText: { fontFamily: fontFamilies.regular, fontSize: 11, color: muted },
  overdueText: { color: '#B42318', fontFamily: fontFamilies.semiBold },
  badge: { borderRadius: 999, backgroundColor: '#F2F4F7', paddingHorizontal: 9, paddingVertical: 5, flexShrink: 0 },
  badgeText: { fontFamily: fontFamilies.semiBold, color: '#475467', fontSize: 11 },
  badgeUrgent: { backgroundColor: '#FEF3F2' },
  badgeUrgentText: { color: '#B42318' },
  caseDetailPane: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: border, borderRadius: 16 },
  caseDetailContent: { padding: 18, paddingBottom: 50 },
  detailTitleBlock: { flex: 1, minWidth: 0 },
  detailImage: { width: '100%', height: 260, borderRadius: 14, backgroundColor: '#EAECF0', marginTop: 12 },
  contextGrid: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 10, marginTop: 14 },
  contextCard: { flexGrow: 1, flexBasis: 250, borderRadius: 13, borderWidth: 1, borderColor: border, backgroundColor: '#F9FAFB', padding: 13, marginTop: 10 },
  contextLinkCard: { borderColor: '#C7D2FE', backgroundColor: '#F8F9FF' },
  contextLinkText: { fontFamily: fontFamilies.bold, color: primary, textAlign: 'right', marginTop: 10, fontSize: 12 },
  timelineItem: { borderTopWidth: 1, borderTopColor: border, paddingTop: 9, marginTop: 9 },
  decisionPanel: { borderRadius: 15, borderWidth: 1, borderColor: '#C7D2FE', backgroundColor: '#F8F9FF', padding: 15, marginTop: 14 },
  dangerZone: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8, borderRadius: 11, borderWidth: 1, borderColor: '#FECDCA', backgroundColor: '#FEF3F2', padding: 10, marginTop: 12 },
  dangerZoneColumn: { borderRadius: 12, borderWidth: 1, borderColor: '#FECDCA', backgroundColor: '#FEF3F2', padding: 12, marginTop: 14 },
  dangerZoneText: { flex: 1, fontFamily: fontFamilies.semiBold, fontSize: 12, lineHeight: 18, color: '#B42318', textAlign: 'right' },

  preview: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 12, marginTop: 12, padding: 12, borderRadius: 13, backgroundColor: '#F9FAFB', borderWidth: 1, borderColor: border },
  previewUnavailable: { flexDirection: 'column', backgroundColor: '#FFFAEB', borderColor: '#FEDF89' },
  previewMissingNotice: { flexBasis: '100%', borderRadius: 9, backgroundColor: '#FFFAEB', paddingHorizontal: 9, paddingVertical: 7 },
  previewMissingNoticeText: { fontFamily: fontFamilies.semiBold, color: '#B54708', textAlign: 'right', fontSize: 12 },
  previewImage: { width: 112, height: 112, borderRadius: 11, backgroundColor: '#EAECF0' },
  previewContent: { flex: 1, minWidth: 0 },
  previewTitle: { fontFamily: fontFamilies.bold, fontSize: 16, color: ink, textAlign: 'right' },
  previewMeta: { fontFamily: fontFamilies.regular, color: muted, textAlign: 'right', marginTop: 4, fontSize: 12 },
  previewText: { fontFamily: fontFamilies.regular, color: '#344054', textAlign: 'right', marginTop: 8, lineHeight: 20 },
  previewToggle: { minHeight: 44, alignSelf: 'flex-end', justifyContent: 'center', marginTop: 2 },
  previewToggleText: { fontFamily: fontFamilies.bold, color: primary, textAlign: 'right' },

  searchResults: { width: '100%', maxWidth: 920, alignSelf: 'center' },
  searchResult: { minHeight: 76, flexDirection: 'row-reverse', alignItems: 'center', gap: 11, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: border, borderRadius: 13, padding: 12, marginBottom: 8 },
  searchResultIcon: { width: 38, height: 38, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEF0FF' },
  searchResultBody: { flex: 1, minWidth: 0 },
  resourceDetail: { width: '100%', maxWidth: 920, alignSelf: 'center', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: border, borderRadius: 15, padding: 16, marginTop: 14 },

  userLayout: { flexDirection: 'row-reverse', flexWrap: 'wrap', alignItems: 'flex-start', gap: 14 },
  userList: { flex: 1, minWidth: 280 },
  userDetail: { flex: 1, minWidth: 300, borderRadius: 15, borderWidth: 1, borderColor: border, backgroundColor: '#FFFFFF', padding: 16 },
  userAvatar: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEF0FF' },
  userAvatarText: { fontFamily: fontFamilies.bold, color: primary, fontSize: 17 },
  advancedToggle: { minHeight: 48, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', gap: 10, borderTopWidth: 1, borderTopColor: border, marginTop: 15, paddingTop: 12 },

  destinationLayout: { flexDirection: 'row-reverse', flexWrap: 'wrap', alignItems: 'flex-start', gap: 14 },
  destinationList: { flex: 0.85, minWidth: 280 },
  destinationDetail: { flex: 1.15, minWidth: 320, borderRadius: 15, borderWidth: 1, borderColor: border, backgroundColor: '#FFFFFF', padding: 16 },
  destinationImageWrap: { width: '100%', height: 220, position: 'relative', overflow: 'hidden', borderRadius: 13, marginTop: 12, backgroundColor: '#EAECF0' },
  destinationImage: { width: '100%', height: '100%' },
  issue: { borderRadius: 9, backgroundColor: '#FFFAEB', paddingHorizontal: 9, paddingVertical: 7, marginTop: 7 },
  issueError: { backgroundColor: '#FEF3F2' },
  candidate: { borderRadius: 12, borderWidth: 1, borderColor: border, padding: 10, marginTop: 10, backgroundColor: '#FFFFFF' },
  candidateImageWrap: { width: '100%', height: 175, position: 'relative', overflow: 'hidden', borderRadius: 10, backgroundColor: '#EAECF0' },
  candidateImage: { width: '100%', height: '100%' },

  auditList: { width: '100%', maxWidth: 920, alignSelf: 'center' },
  auditRow: { flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 12, paddingBottom: 18 },
  timelineDot: { width: 11, height: 11, borderRadius: 6, backgroundColor: primary, marginTop: 6 },
  auditBody: { flex: 1, borderBottomWidth: 1, borderBottomColor: border, paddingBottom: 16 },
});

export { colors };
