import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const atlasStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.atlasNight, alignItems: 'center' },
  frame: { flex: 1, maxWidth: '100%' },
  scrollContent: { flexGrow: 1, paddingBottom: 2 },
  fill: { ...StyleSheet.absoluteFill, width: '100%', height: '100%' },
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 8 },
  brandRow: { flexDirection: 'row', writingDirection: 'ltr', alignItems: 'center', justifyContent: 'space-between', minHeight: 44, marginBottom: 6 },
  logo: { fontSize: 29, color: colors.white, writingDirection: 'ltr' },
  logoGold: { fontSize: 29, color: colors.atlasGold },
  title: { fontSize: 35, lineHeight: 38, textAlign: 'center', color: colors.white },
  gold: { color: colors.atlasGold },
  subtitle: { fontSize: 15, lineHeight: 20, textAlign: 'center', color: colors.atlasMist, marginTop: 6 },
  close: { borderWidth: 1, borderColor: 'rgba(255,255,255,.5)', borderRadius: 24, minHeight: 44, minWidth: 80, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' },
  closeSpace: { height: 44 },
  closeText: { color: colors.white, fontSize: 14 },
  globe: { width: '100%', position: 'relative', flexShrink: 0 },
  hiddenGlobe: { opacity: 0 },
  rotate: { position: 'absolute', bottom: 10, width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: 'rgba(255,255,255,.6)', alignItems: 'center', justifyContent: 'center', backgroundColor: colors.atlasNight },
  rotateLeft: { left: 14 },
  rotateRight: { right: 14 },
  hintRow: { minHeight: 44, flexDirection: 'row-reverse', justifyContent: 'center', alignItems: 'center', gap: 4, paddingHorizontal: 16 },
  hint: { color: colors.atlasMist, fontSize: 13, lineHeight: 20, textAlign: 'center', flexShrink: 1 },
  spin: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  photoCard: { marginHorizontal: 20, borderRadius: 22, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(255,255,255,.35)', justifyContent: 'flex-end', backgroundColor: '#23495C' },
  collage: { flexDirection: 'row', gap: 3 },
  collagePhoto: { flex: 1, height: '100%' },
  photoCopy: { paddingHorizontal: 18, paddingBottom: 16, paddingTop: 74, alignItems: 'stretch' },
  eyebrow: { fontSize: 12, lineHeight: 18, color: colors.atlasGold, textAlign: 'right', writingDirection: 'rtl' },
  regionTitle: { fontSize: 29, lineHeight: 34, color: colors.white, textAlign: 'right', writingDirection: 'rtl' },
  description: { fontSize: 14, lineHeight: 20, color: colors.white, textAlign: 'right', writingDirection: 'rtl', marginTop: 2 },
  choicesRow: { flexDirection: 'row-reverse', minHeight: 64, alignItems: 'center', gap: 8, paddingRight: 20, paddingVertical: 10 },
  globalChip: { flexDirection: 'row-reverse', gap: 6 },
  regionScroll: { flex: 1, writingDirection: 'ltr' },
  regionChoices: { flexDirection: 'row', gap: 8, alignItems: 'center', paddingLeft: 20, paddingRight: 2 },
  chip: { minHeight: 44, borderWidth: 1, borderColor: 'rgba(255,255,255,.45)', borderRadius: 24, paddingHorizontal: 14, paddingVertical: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.025)' },
  chipText: { fontSize: 14, lineHeight: 20, color: colors.white, textAlign: 'center' },
  selectedChip: { backgroundColor: '#FAF7F2', borderColor: '#FAF7F2' },
  selectedChipText: { color: '#172C43' },
  footer: { paddingHorizontal: 20, paddingTop: 2, paddingBottom: 16, backgroundColor: colors.atlasNight },
  confirm: { minHeight: 50, paddingHorizontal: 12, paddingVertical: 12, flexDirection: 'row', writingDirection: 'ltr', gap: 10, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: colors.secondary },
  confirmText: { fontSize: 17, lineHeight: 24, textAlign: 'center', color: '#172C43', flexShrink: 1 },
  pressed: { opacity: .75 },
  busy: { opacity: .8 },
  notice: { paddingHorizontal: 20, alignItems: 'center', paddingBottom: 8 },
  retry: { minHeight: 44, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center' },
  saveError: { fontSize: 14, lineHeight: 20, color: colors.atlasGold, textAlign: 'center', marginBottom: 8 },
});
