import { StyleSheet } from 'react-native';
import { fontFamilies } from './typography';

export const authStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F4F5F9' },
  keyboard: { flex: 1 },
  welcomeSafe: { flex: 1, backgroundColor: 'transparent' },
  welcomeGradient: { flex: 1, backgroundColor: '#FFFFFF' },
  welcomeAccessibleContent: { flexGrow: 1 },
  welcomeContent: { flex: 1, width: '100%', maxWidth: 460, alignSelf: 'center' },
  welcomeHero: { flex: 0.44, minHeight: 238, alignItems: 'center', overflow: 'hidden' },
  welcomeWordmarkCapsule: { position: 'absolute', top: 8, zIndex: 3, height: 60, minWidth: 214, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  welcomeWordmark: { width: 188, height: 63, alignSelf: 'center' },
  welcomeArtwork: { flex: 1, width: '100%', alignItems: 'center', justifyContent: 'center' },
  welcomeArtworkImage: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  welcomeMarkHalo: { position: 'absolute', top: 70, zIndex: 2, width: 132, height: 132 },
  welcomeMark: { width: '100%', height: '100%' },
  welcomeSheet: { flex: 0.56, minHeight: 340, backgroundColor: '#FFFFFF', borderTopLeftRadius: 32, borderTopRightRadius: 32, paddingHorizontal: 24, paddingTop: 22, paddingBottom: 4, shadowColor: '#102A43', shadowOffset: { width: 0, height: -8 }, shadowOpacity: 0.08, shadowRadius: 20, elevation: 8 },
  welcomeTitle: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 30, lineHeight: 36, textAlign: 'center', writingDirection: 'rtl' },
  welcomeSubtitle: { color: '#5D6B7A', fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 21, textAlign: 'center', writingDirection: 'rtl', marginTop: 5, marginBottom: 13 },
  welcomePrimaryButton: { minHeight: 50, borderRadius: 25, backgroundColor: '#1E3A5F', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  welcomeSecondaryButton: { minHeight: 50, borderRadius: 25, borderWidth: 1.5, borderColor: '#F5961D', backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, marginTop: 10 },
  welcomeSecondaryButtonText: { color: '#D97706', fontFamily: fontFamilies.semiBold, fontSize: 16 },
  welcomeErrorSlot: { minHeight: 24, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  welcomeError: { color: '#B42318', fontFamily: fontFamilies.medium, fontSize: 12, lineHeight: 17, textAlign: 'center', writingDirection: 'rtl' },
  welcomeGuestButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 1 },
  welcomeGuestText: { color: '#1E3A5F', fontFamily: fontFamilies.medium, fontSize: 14, textAlign: 'center', writingDirection: 'rtl' },
  formSafe: { flex: 1, backgroundColor: '#FFFFFF' },
  formGradient: { flex: 1, overflow: 'hidden' },
  formAccessibleScroll: { flex: 1 },
  formAccessibleScrollContent: { flexGrow: 1 },
  formDecoration: { ...StyleSheet.absoluteFillObject },
  formRouteArtwork: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 126 },
  formShell: { width: '100%', maxWidth: 460, alignSelf: 'center', justifyContent: 'flex-start', paddingHorizontal: 20, paddingTop: 24, paddingBottom: 8 },
  formShellStatic: { flex: 1 },
  formShellAccessible: { flexGrow: 1 },
  formShellCompact: { paddingTop: 8, paddingBottom: 4 },
  formShellEditing: { justifyContent: 'flex-start', paddingTop: 4, paddingBottom: 2 },
  formCard: { width: '100%', backgroundColor: '#FFFFFF', borderRadius: 0, paddingHorizontal: 0, paddingTop: 0, paddingBottom: 0 },
  formCardCompact: { paddingHorizontal: 0, paddingTop: 0, paddingBottom: 0, borderRadius: 0 },
  formCardEditing: { paddingTop: 0, paddingBottom: 0 },
  formBackButton: { position: 'absolute', top: 0, right: -4, zIndex: 2, width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: 'transparent' },
  formBrand: { minHeight: 62, alignItems: 'center', justifyContent: 'center', marginBottom: 14 },
  formLogo: { width: 188, height: 63, alignSelf: 'center' },
  formTitle: { fontFamily: fontFamilies.semiBold, fontSize: 31, lineHeight: 37, color: '#1E3A5F', textAlign: 'center', writingDirection: 'rtl' },
  formTitleCompact: { fontSize: 25, lineHeight: 30 },
  formSubtitle: { fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 21, color: '#1E3A5F', textAlign: 'center', writingDirection: 'rtl', marginTop: 5, marginBottom: 22 },
  formFields: { width: '100%' },
  scroll: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 24 },
  shell: { width: '100%', maxWidth: 460, alignSelf: 'center', paddingHorizontal: 20 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 22, shadowColor: '#102A43', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.08, shadowRadius: 20, elevation: 3 },
  backRow: { minHeight: 44, flexDirection: 'row-reverse', justifyContent: 'flex-start', marginBottom: 2 },
  backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: '#F4F5F9' },
  logo: { width: 244, height: 82, alignSelf: 'center', marginBottom: 22 },
  compactLogo: { width: 174, height: 58, alignSelf: 'center', marginBottom: 18 },
  title: { fontFamily: fontFamilies.semiBold, fontSize: 28, lineHeight: 34, color: '#1E3A5F', textAlign: 'right', writingDirection: 'rtl' },
  centeredTitle: { textAlign: 'center' },
  subtitle: { fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 22, color: '#5D6B7A', textAlign: 'right', writingDirection: 'rtl', marginTop: 7, marginBottom: 22 },
  centeredText: { textAlign: 'center' },
  field: { marginBottom: 12 },
  compactField: { marginBottom: 7 },
  editingField: { marginBottom: 3 },
  label: { fontFamily: fontFamilies.medium, fontSize: 14, color: '#1F2937', textAlign: 'right', writingDirection: 'rtl', marginBottom: 7 },
  compactLabel: { fontSize: 12, lineHeight: 15, marginBottom: 2, paddingRight: 3 },
  inputRow: { minHeight: 66, flexDirection: 'row-reverse', alignItems: 'center', borderWidth: 1, borderColor: '#D9E0E8', backgroundColor: '#FFFFFF', borderRadius: 13, paddingHorizontal: 14 },
  compactInputRow: { minHeight: 50, borderRadius: 12, paddingHorizontal: 12 },
  embeddedInputContent: { flex: 1, alignSelf: 'stretch', justifyContent: 'center' },
  embeddedInputLabel: { color: '#4B5563', fontFamily: fontFamilies.regular, fontSize: 12, lineHeight: 15, textAlign: 'right', writingDirection: 'rtl', paddingTop: 5 },
  compactEmbeddedInputLabel: { fontSize: 11, lineHeight: 13, paddingTop: 2 },
  input: { flex: 1, fontSize: 16, color: '#111827', textAlign: 'right', writingDirection: 'rtl', paddingVertical: 8 },
  compactInput: { fontSize: 15, paddingVertical: 4 },
  embeddedInput: { paddingTop: 0, paddingBottom: 6 },
  compactEmbeddedInput: { paddingTop: 0, paddingBottom: 3 },
  inputIcon: { marginLeft: 10 },
  eyeButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginRight: -8 },
  linkButton: { minHeight: 44, justifyContent: 'center', alignSelf: 'flex-start' },
  link: { color: '#175EC7', fontFamily: fontFamilies.semiBold, fontSize: 14, textAlign: 'right' },
  error: { color: '#B42318', fontFamily: fontFamilies.medium, fontSize: 13, lineHeight: 19, textAlign: 'right', writingDirection: 'rtl', marginBottom: 12 },
  formErrorSlot: { minHeight: 32, justifyContent: 'center' },
  formError: { marginBottom: 0 },
  primaryButton: { minHeight: 52, borderRadius: 14, backgroundColor: '#1E3A5F', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, marginTop: 4 },
  formPrimaryButton: { minHeight: 50, borderRadius: 25, marginTop: 0, shadowColor: '#1E3A5F', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.16, shadowRadius: 9, elevation: 3 },
  primaryButtonDisabled: { opacity: 0.55 },
  primaryButtonText: { color: '#FFFFFF', fontFamily: fontFamilies.semiBold, fontSize: 16 },
  secondaryButton: { minHeight: 52, borderRadius: 14, borderWidth: 1, borderColor: '#1E3A5F', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, marginTop: 12, backgroundColor: '#FFFFFF' },
  secondaryButtonText: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 16 },
  textButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  textButtonText: { color: '#52606D', fontFamily: fontFamilies.medium, fontSize: 14 },
  dividerRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 20 },
  formDividerRow: { marginVertical: 8 },
  divider: { flex: 1, height: 1, backgroundColor: '#E5E9EF' },
  dividerText: { marginHorizontal: 12, color: '#7B8794', fontFamily: fontFamilies.regular, fontSize: 13 },
  socialRow: { gap: 12, alignItems: 'center' },
  googleButton: { width: '100%', height: 52 },
  appleButton: { width: '100%', height: 52 },
  footerRow: { flexDirection: 'row-reverse', justifyContent: 'center', alignItems: 'center', flexWrap: 'wrap', marginTop: 18 },
  formFooterRow: { minHeight: 44, marginTop: 7 },
  footerText: { color: '#5D6B7A', fontFamily: fontFamilies.regular, fontSize: 14 },
  checkboxRow: { flexDirection: 'row-reverse', alignItems: 'flex-start', marginVertical: 8 },
  compactCheckboxRow: { minHeight: 44, marginVertical: 0, alignItems: 'center' },
  checkbox: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: 2 },
  consentText: { flex: 1, color: '#4B5563', fontFamily: fontFamilies.regular, fontSize: 13, lineHeight: 21, textAlign: 'right', writingDirection: 'rtl', paddingTop: 10 },
  compactConsentText: { fontSize: 12, lineHeight: 18, paddingTop: 0 },
  inlineLink: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold },
  strengthTrack: { height: 5, borderRadius: 999, overflow: 'hidden', backgroundColor: '#E8ECF1', marginTop: -7, marginBottom: 14 },
  compactStrengthTrack: { height: 4, marginTop: -3, marginBottom: 7 },
  strengthFill: { height: '100%', borderRadius: 999, backgroundColor: '#F5961D' },
  statusIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#FFF3DE', alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginBottom: 16 },
  email: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 15, textAlign: 'center', writingDirection: 'ltr', marginBottom: 12 },
  utilityRow: { flexDirection: 'row-reverse', justifyContent: 'center', flexWrap: 'wrap', marginTop: 10 },
  utilityLink: { minHeight: 44, paddingHorizontal: 10, justifyContent: 'center' },
  utilityText: { color: '#667085', fontFamily: fontFamilies.medium, fontSize: 13 },
  legalSafe: { flex: 1, backgroundColor: '#F4F5F9' },
  legalHeader: { flexDirection: 'row-reverse', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 10, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E9EF' },
  legalBack: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  legalHeaderTitle: { flex: 1, color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 20, textAlign: 'right' },
  legalContent: { width: '100%', maxWidth: 760, alignSelf: 'center', padding: 20, paddingBottom: 48 },
  legalMeta: { color: '#667085', fontFamily: fontFamilies.regular, fontSize: 13, textAlign: 'right', writingDirection: 'rtl', marginBottom: 16 },
  legalIntro: { color: '#344054', fontFamily: fontFamilies.medium, fontSize: 15, lineHeight: 23, textAlign: 'right', writingDirection: 'rtl', marginBottom: 20 },
  legalSection: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 18, marginBottom: 12 },
  legalSectionTitle: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 18, textAlign: 'right', writingDirection: 'rtl', marginBottom: 8 },
  legalBody: { color: '#475467', fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 24, textAlign: 'right', writingDirection: 'rtl' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(16, 24, 40, 0.48)', justifyContent: 'flex-end', padding: 16 },
  modalCard: { width: '100%', maxWidth: 420, alignSelf: 'center', backgroundColor: '#FFFFFF', borderRadius: 24, padding: 22, marginBottom: 14 },
  modalIcon: { width: 52, height: 52, borderRadius: 26, backgroundColor: '#FFF3DE', alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-end', marginBottom: 12 },
  modalTitle: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 22, textAlign: 'right', writingDirection: 'rtl' },
  modalBody: { color: '#52606D', fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 22, textAlign: 'right', writingDirection: 'rtl', marginTop: 8, marginBottom: 14 },
});
