import { StyleSheet } from 'react-native';
import { fontFamilies } from './typography';

export const authStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F4F5F9' },
  keyboard: { flex: 1 },
  scroll: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 24 },
  shell: { width: '100%', maxWidth: 460, alignSelf: 'center', paddingHorizontal: 20 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 22, shadowColor: '#102A43', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.08, shadowRadius: 20, elevation: 3 },
  logo: { width: 244, height: 82, alignSelf: 'center', marginBottom: 22 },
  compactLogo: { width: 174, height: 58, alignSelf: 'center', marginBottom: 18 },
  title: { fontFamily: fontFamilies.semiBold, fontSize: 28, lineHeight: 34, color: '#1E3A5F', textAlign: 'right', writingDirection: 'rtl' },
  centeredTitle: { textAlign: 'center' },
  subtitle: { fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 22, color: '#5D6B7A', textAlign: 'right', writingDirection: 'rtl', marginTop: 7, marginBottom: 22 },
  centeredText: { textAlign: 'center' },
  field: { marginBottom: 15 },
  label: { fontFamily: fontFamilies.medium, fontSize: 14, color: '#1F2937', textAlign: 'right', writingDirection: 'rtl', marginBottom: 7 },
  inputRow: { minHeight: 52, flexDirection: 'row-reverse', alignItems: 'center', borderWidth: 1, borderColor: '#D9E0E8', backgroundColor: '#FBFCFE', borderRadius: 14, paddingHorizontal: 14 },
  input: { flex: 1, fontSize: 16, color: '#111827', textAlign: 'right', writingDirection: 'rtl', paddingVertical: 12 },
  inputIcon: { marginLeft: 10 },
  eyeButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginRight: -8 },
  linkButton: { minHeight: 44, justifyContent: 'center', alignSelf: 'flex-end' },
  link: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 14, textAlign: 'right' },
  error: { color: '#B42318', fontFamily: fontFamilies.medium, fontSize: 13, lineHeight: 19, textAlign: 'right', writingDirection: 'rtl', marginBottom: 12 },
  primaryButton: { minHeight: 52, borderRadius: 14, backgroundColor: '#1E3A5F', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, marginTop: 4 },
  primaryButtonDisabled: { opacity: 0.55 },
  primaryButtonText: { color: '#FFFFFF', fontFamily: fontFamilies.semiBold, fontSize: 16 },
  secondaryButton: { minHeight: 52, borderRadius: 14, borderWidth: 1, borderColor: '#1E3A5F', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, marginTop: 12, backgroundColor: '#FFFFFF' },
  secondaryButtonText: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 16 },
  textButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  textButtonText: { color: '#52606D', fontFamily: fontFamilies.medium, fontSize: 14 },
  dividerRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 20 },
  divider: { flex: 1, height: 1, backgroundColor: '#E5E9EF' },
  dividerText: { marginHorizontal: 12, color: '#7B8794', fontFamily: fontFamilies.regular, fontSize: 13 },
  socialRow: { gap: 12, alignItems: 'center' },
  googleButton: { width: '100%', height: 52 },
  appleButton: { width: '100%', height: 52 },
  footerRow: { flexDirection: 'row-reverse', justifyContent: 'center', alignItems: 'center', flexWrap: 'wrap', marginTop: 18 },
  footerText: { color: '#5D6B7A', fontFamily: fontFamilies.regular, fontSize: 14 },
  checkboxRow: { flexDirection: 'row-reverse', alignItems: 'flex-start', marginVertical: 8 },
  checkbox: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: 2 },
  consentText: { flex: 1, color: '#4B5563', fontFamily: fontFamilies.regular, fontSize: 13, lineHeight: 21, textAlign: 'right', writingDirection: 'rtl', paddingTop: 10 },
  inlineLink: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold },
  strengthTrack: { height: 5, borderRadius: 999, overflow: 'hidden', backgroundColor: '#E8ECF1', marginTop: -7, marginBottom: 14 },
  strengthFill: { height: '100%', borderRadius: 999, backgroundColor: '#F5961D' },
  statusIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#FFF3DE', alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginBottom: 16 },
  email: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 15, textAlign: 'center', writingDirection: 'ltr', marginBottom: 12 },
  utilityRow: { flexDirection: 'row-reverse', justifyContent: 'center', flexWrap: 'wrap', marginTop: 10 },
  utilityLink: { minHeight: 44, paddingHorizontal: 10, justifyContent: 'center' },
  utilityText: { color: '#667085', fontFamily: fontFamilies.medium, fontSize: 13 },
  legalSafe: { flex: 1, backgroundColor: '#F4F5F9' },
  legalHeader: { flexDirection: 'row-reverse', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 10, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E9EF' },
  legalBack: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  legalHeaderTitle: { flex: 1, color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 20, textAlign: 'right' },
  legalContent: { width: '100%', maxWidth: 760, alignSelf: 'center', padding: 20, paddingBottom: 48 },
  legalMeta: { color: '#667085', fontFamily: fontFamilies.regular, fontSize: 13, textAlign: 'right', writingDirection: 'rtl', marginBottom: 16 },
  legalIntro: { color: '#344054', fontFamily: fontFamilies.medium, fontSize: 15, lineHeight: 23, textAlign: 'right', writingDirection: 'rtl', marginBottom: 20 },
  legalSection: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 18, marginBottom: 12 },
  legalSectionTitle: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 18, textAlign: 'right', writingDirection: 'rtl', marginBottom: 8 },
  legalBody: { color: '#475467', fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 24, textAlign: 'right', writingDirection: 'rtl' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(16, 24, 40, 0.48)', justifyContent: 'flex-end', padding: 16 },
  modalCard: { width: '100%', maxWidth: 420, alignSelf: 'center', backgroundColor: '#FFFFFF', borderRadius: 24, padding: 22, marginBottom: 14 },
  modalIcon: { width: 52, height: 52, borderRadius: 26, backgroundColor: '#FFF3DE', alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-end', marginBottom: 12 },
  modalTitle: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 22, textAlign: 'right', writingDirection: 'rtl' },
  modalBody: { color: '#52606D', fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 22, textAlign: 'right', writingDirection: 'rtl', marginTop: 8, marginBottom: 14 },
});
