import { StyleSheet } from 'react-native';
import { fontFamilies } from './typography';

export const authStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F4F5F9' },
  keyboard: { flex: 1 },
  welcomeSafe: { flex: 1, backgroundColor: '#FFF0D2' },
  welcomeGradient: { flex: 1 },
  welcomeAccessibleContent: { flexGrow: 1 },
  welcomeContent: { flex: 1, width: '100%', maxWidth: 460, alignSelf: 'center' },
  welcomeHero: { flex: 0.38, minHeight: 216, alignItems: 'center', paddingTop: 4, overflow: 'hidden' },
  welcomeWordmarkCapsule: { height: 48, minWidth: 184, paddingHorizontal: 12, borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255, 255, 255, 0.94)', shadowColor: '#1E3A5F', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.09, shadowRadius: 10, elevation: 3, zIndex: 2 },
  welcomeWordmark: { width: 160, height: 53, alignSelf: 'center' },
  welcomeArtwork: { flex: 1, width: '100%', minHeight: 160, marginTop: -2, alignItems: 'center', justifyContent: 'center' },
  welcomeMarkHalo: { position: 'absolute', top: 15, width: 116, height: 116, borderRadius: 58, overflow: 'hidden', backgroundColor: '#FFFFFF', borderWidth: 5, borderColor: 'rgba(255, 255, 255, 0.92)', shadowColor: '#102A43', shadowOffset: { width: 0, height: 7 }, shadowOpacity: 0.16, shadowRadius: 14, elevation: 5 },
  welcomeMark: { width: '100%', height: '100%' },
  welcomeSheet: { flex: 0.62, minHeight: 376, backgroundColor: '#FFFFFF', borderTopLeftRadius: 32, borderTopRightRadius: 32, paddingHorizontal: 22, paddingTop: 18, paddingBottom: 8, shadowColor: '#102A43', shadowOffset: { width: 0, height: -8 }, shadowOpacity: 0.08, shadowRadius: 20, elevation: 8 },
  welcomeTitle: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 29, lineHeight: 35, textAlign: 'center', writingDirection: 'rtl' },
  welcomeSubtitle: { color: '#5D6B7A', fontFamily: fontFamilies.regular, fontSize: 14, lineHeight: 20, textAlign: 'center', writingDirection: 'rtl', marginTop: 4, marginBottom: 10 },
  welcomePrimaryButton: { minHeight: 48, borderRadius: 24, backgroundColor: '#1E3A5F', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  welcomeSecondaryButton: { minHeight: 48, borderRadius: 24, borderWidth: 1.5, borderColor: '#F5961D', backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, marginTop: 9 },
  welcomeSecondaryButtonText: { color: '#D97706', fontFamily: fontFamilies.semiBold, fontSize: 16 },
  welcomeErrorSlot: { minHeight: 28, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  welcomeError: { color: '#B42318', fontFamily: fontFamilies.medium, fontSize: 12, lineHeight: 17, textAlign: 'center', writingDirection: 'rtl' },
  welcomeGuestButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  welcomeGuestText: { color: '#52606D', fontFamily: fontFamilies.medium, fontSize: 14, textAlign: 'center', writingDirection: 'rtl' },
  formSafe: { flex: 1, backgroundColor: '#FFFFFF' },
  formGradient: { flex: 1, overflow: 'hidden' },
  formAccessibleScroll: { flex: 1 },
  formAccessibleScrollContent: { flexGrow: 1 },
  formDecoration: { ...StyleSheet.absoluteFillObject },
  formDecorationNavy: { position: 'absolute', width: 190, height: 190, borderRadius: 95, backgroundColor: 'rgba(30, 58, 95, 0.045)', top: -118, left: -82 },
  formDecorationOrange: { position: 'absolute', width: 118, height: 118, borderRadius: 59, backgroundColor: 'rgba(245, 150, 29, 0.09)', top: -52, right: -34 },
  formRouteLine: { position: 'absolute', width: 210, height: 82, borderRadius: 44, borderWidth: 3, borderStyle: 'dashed', borderColor: 'rgba(245, 150, 29, 0.14)', borderLeftColor: 'transparent', borderTopColor: 'transparent', bottom: 16, left: -18, transform: [{ rotate: '8deg' }] },
  formShell: { width: '100%', maxWidth: 460, alignSelf: 'center', justifyContent: 'center', paddingHorizontal: 16, paddingVertical: 14 },
  formShellStatic: { flex: 1 },
  formShellAccessible: { flexGrow: 1 },
  formShellCompact: { paddingVertical: 8 },
  formShellEditing: { justifyContent: 'flex-start', paddingTop: 4, paddingBottom: 2 },
  formCard: { width: '100%', backgroundColor: 'rgba(255, 255, 255, 0.88)', borderRadius: 24, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 16 },
  formCardCompact: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 10, borderRadius: 20 },
  formCardEditing: { paddingTop: 8, paddingBottom: 6 },
  formBackButton: { position: 'absolute', top: 8, right: 8, zIndex: 2, width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: '#F7F9FC', borderWidth: 1, borderColor: '#E7ECF2' },
  formBrand: { minHeight: 56, alignItems: 'center', justifyContent: 'center', marginBottom: 5 },
  formLogo: { width: 160, height: 53, alignSelf: 'center' },
  formTitle: { fontFamily: fontFamilies.semiBold, fontSize: 29, lineHeight: 35, color: '#1E3A5F', textAlign: 'right', writingDirection: 'rtl', paddingRight: 2 },
  formTitleCompact: { fontSize: 23, lineHeight: 28 },
  formSubtitle: { fontFamily: fontFamilies.regular, fontSize: 14, lineHeight: 20, color: '#5D6B7A', textAlign: 'right', writingDirection: 'rtl', marginTop: 3, marginBottom: 12, paddingRight: 2 },
  formFields: { width: '100%' },
  scroll: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 24 },
  shell: { width: '100%', maxWidth: 460, alignSelf: 'center', paddingHorizontal: 20 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 22, shadowColor: '#102A43', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.08, shadowRadius: 20, elevation: 3 },
  backRow: { minHeight: 44, flexDirection: 'row-reverse', justifyContent: 'flex-start', marginBottom: 2 },
  backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: '#F4F5F9' },
  logo: { width: 244, height: 82, alignSelf: 'center', marginBottom: 22 },
  compactLogo: { width: 174, height: 58, alignSelf: 'center', marginBottom: 18 },
  title: { fontFamily: fontFamilies.semiBold, fontSize: 28, lineHeight: 34, color: '#1E3A5F', textAlign: 'right', writingDirection: 'rtl' },
  centeredTitle: { textAlign: 'center' },
  subtitle: { fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 22, color: '#5D6B7A', textAlign: 'right', writingDirection: 'rtl', marginTop: 7, marginBottom: 22 },
  centeredText: { textAlign: 'center' },
  field: { marginBottom: 15 },
  compactField: { marginBottom: 7 },
  editingField: { marginBottom: 3 },
  label: { fontFamily: fontFamilies.medium, fontSize: 14, color: '#1F2937', textAlign: 'right', writingDirection: 'rtl', marginBottom: 7 },
  compactLabel: { fontSize: 12, lineHeight: 15, marginBottom: 2, paddingRight: 3 },
  inputRow: { minHeight: 52, flexDirection: 'row-reverse', alignItems: 'center', borderWidth: 1, borderColor: '#D9E0E8', backgroundColor: '#FBFCFE', borderRadius: 14, paddingHorizontal: 14 },
  compactInputRow: { minHeight: 44, borderRadius: 12, paddingHorizontal: 12 },
  input: { flex: 1, fontSize: 16, color: '#111827', textAlign: 'right', writingDirection: 'rtl', paddingVertical: 12 },
  compactInput: { fontSize: 15, paddingVertical: 9 },
  inputIcon: { marginLeft: 10 },
  eyeButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginRight: -8 },
  linkButton: { minHeight: 44, justifyContent: 'center', alignSelf: 'flex-end' },
  link: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 14, textAlign: 'right' },
  error: { color: '#B42318', fontFamily: fontFamilies.medium, fontSize: 13, lineHeight: 19, textAlign: 'right', writingDirection: 'rtl', marginBottom: 12 },
  formErrorSlot: { minHeight: 38, justifyContent: 'center' },
  formError: { marginBottom: 0 },
  primaryButton: { minHeight: 52, borderRadius: 14, backgroundColor: '#1E3A5F', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, marginTop: 4 },
  formPrimaryButton: { minHeight: 48, marginTop: 0, shadowColor: '#1E3A5F', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.18, shadowRadius: 9, elevation: 3 },
  primaryButtonDisabled: { opacity: 0.55 },
  primaryButtonText: { color: '#FFFFFF', fontFamily: fontFamilies.semiBold, fontSize: 16 },
  secondaryButton: { minHeight: 52, borderRadius: 14, borderWidth: 1, borderColor: '#1E3A5F', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, marginTop: 12, backgroundColor: '#FFFFFF' },
  secondaryButtonText: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 16 },
  textButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  textButtonText: { color: '#52606D', fontFamily: fontFamilies.medium, fontSize: 14 },
  dividerRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 20 },
  formDividerRow: { marginVertical: 8 },
  divider: { flex: 1, height: 1, backgroundColor: '#E5E9EF' },
  dividerText: { marginHorizontal: 12, color: '#7B8794', fontFamily: fontFamilies.regular, fontSize: 13 },
  socialRow: { gap: 12, alignItems: 'center' },
  googleButton: { width: '100%', height: 52 },
  appleButton: { width: '100%', height: 52 },
  footerRow: { flexDirection: 'row-reverse', justifyContent: 'center', alignItems: 'center', flexWrap: 'wrap', marginTop: 18 },
  formFooterRow: { minHeight: 44, marginTop: 4 },
  footerText: { color: '#5D6B7A', fontFamily: fontFamilies.regular, fontSize: 14 },
  checkboxRow: { flexDirection: 'row-reverse', alignItems: 'flex-start', marginVertical: 8 },
  compactCheckboxRow: { minHeight: 44, marginVertical: 0, alignItems: 'center' },
  checkbox: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: 2 },
  consentText: { flex: 1, color: '#4B5563', fontFamily: fontFamilies.regular, fontSize: 13, lineHeight: 21, textAlign: 'right', writingDirection: 'rtl', paddingTop: 10 },
  compactConsentText: { fontSize: 12, lineHeight: 18, paddingTop: 0 },
  inlineLink: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold },
  strengthTrack: { height: 5, borderRadius: 999, overflow: 'hidden', backgroundColor: '#E8ECF1', marginTop: -7, marginBottom: 14 },
  compactStrengthTrack: { height: 4, marginTop: -3, marginBottom: 7 },
  strengthFill: { height: '100%', borderRadius: 999, backgroundColor: '#F5961D' },
  statusIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#FFF3DE', alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginBottom: 16 },
  email: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 15, textAlign: 'center', writingDirection: 'ltr', marginBottom: 12 },
  utilityRow: { flexDirection: 'row-reverse', justifyContent: 'center', flexWrap: 'wrap', marginTop: 10 },
  utilityLink: { minHeight: 44, paddingHorizontal: 10, justifyContent: 'center' },
  utilityText: { color: '#667085', fontFamily: fontFamilies.medium, fontSize: 13 },
  legalSafe: { flex: 1, backgroundColor: '#F4F5F9' },
  legalHeader: { flexDirection: 'row-reverse', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 10, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E9EF' },
  legalBack: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  legalHeaderTitle: { flex: 1, color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 20, textAlign: 'right' },
  legalContent: { width: '100%', maxWidth: 760, alignSelf: 'center', padding: 20, paddingBottom: 48 },
  legalMeta: { color: '#667085', fontFamily: fontFamilies.regular, fontSize: 13, textAlign: 'right', writingDirection: 'rtl', marginBottom: 16 },
  legalIntro: { color: '#344054', fontFamily: fontFamilies.medium, fontSize: 15, lineHeight: 23, textAlign: 'right', writingDirection: 'rtl', marginBottom: 20 },
  legalSection: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 18, marginBottom: 12 },
  legalSectionTitle: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 18, textAlign: 'right', writingDirection: 'rtl', marginBottom: 8 },
  legalBody: { color: '#475467', fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 24, textAlign: 'right', writingDirection: 'rtl' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(16, 24, 40, 0.48)', justifyContent: 'flex-end', padding: 16 },
  modalCard: { width: '100%', maxWidth: 420, alignSelf: 'center', backgroundColor: '#FFFFFF', borderRadius: 24, padding: 22, marginBottom: 14 },
  modalIcon: { width: 52, height: 52, borderRadius: 26, backgroundColor: '#FFF3DE', alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-end', marginBottom: 12 },
  modalTitle: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold, fontSize: 22, textAlign: 'right', writingDirection: 'rtl' },
  modalBody: { color: '#52606D', fontFamily: fontFamilies.regular, fontSize: 15, lineHeight: 22, textAlign: 'right', writingDirection: 'rtl', marginTop: 8, marginBottom: 14 },
});
