import { fontFamilies } from "./typography";
import { colors } from "./colors";
import { shadows } from "./shadows";
import { spacing } from "./spacing";
import { typography } from "./typography";

export const community = {
	// Screen
	screen: {
		flex: 1,
		backgroundColor: colors.background,
	},

	// Header sort button
	sortButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: 2,
	},
	sortButtonText: {
		...typography.caption,
		fontFamily: fontFamilies.semiBold,
		color: colors.textPrimary,
	},

	// Destination search
	destinationSearchWrap: {
		paddingHorizontal: spacing.lg,
		paddingTop: 0,
		paddingBottom: spacing.xs,
	},
	destinationSearchRow: {
		flexDirection: "row-reverse",
		alignItems: "center",
		gap: spacing.sm,
	},
	destinationFilterBtn: {
		width: 36,
		height: 36,
		borderRadius: 18,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: colors.card,
		borderWidth: 1,
		borderColor: colors.borderLight || colors.border,
		...shadows.small,
	},
	destinationSearchPill: {
		flex: 1,
		flexDirection: "row-reverse",
		alignItems: "center",
		gap: spacing.sm,
		backgroundColor: colors.card,
		borderWidth: 1,
		borderColor: colors.borderLight || colors.border,
		borderRadius: 18,
		paddingHorizontal: spacing.md,
		height: 36,
		...shadows.small,
	},
	destinationSearchInput: {
		flex: 1,
		color: colors.textPrimary,
		fontSize: 14,
		paddingVertical: 0,
		writingDirection: "rtl",
	},
	destinationClearBtn: {
		alignItems: "center",
		justifyContent: "center",
	},

	// Sort menu modal
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.3)",
		justifyContent: "center",
		alignItems: "center",
	},
	sortMenu: {
		width: 220,
		backgroundColor: colors.card,
		borderRadius: 12,
		padding: spacing.md,
		elevation: 5,
	},
	sortTitle: {
		...typography.h3,
		textAlign: "center",
		marginBottom: spacing.md,
	},
	sortOption: {
		flexDirection: "row-reverse",
		justifyContent: "space-between",
		paddingVertical: 12,
		borderBottomWidth: 1,
		borderBottomColor: colors.borderLight,
	},
	sortOptionSelected: {
		backgroundColor: colors.background,
	},
	sortOptionLabelRow: {
		flexDirection: "row-reverse",
		alignItems: "center",
	},
	sortOptionIcon: {
		marginLeft: 6,
	},
	sortOptionText: {
		color: colors.textPrimary,
	},
	sortOptionTextSelected: {
		color: colors.primary,
	},

	// Header map button
	headerIconButton: {
		paddingVertical: 6,
		paddingHorizontal: 10,
		borderRadius: 12,
		backgroundColor: colors.card,
		borderWidth: 1,
		borderColor: colors.borderLight || colors.border,
	},
	headerIconButtonText: {
		...typography.caption,
		color: colors.textPrimary,
		fontFamily: fontFamilies.semiBold,
	},

	// Map screen
	mapScreen: {
		flex: 1,
		backgroundColor: colors.background,
	},
	inlineMapSection: {
		flex: 1,
		paddingHorizontal: 0,
		paddingTop: 0,
		paddingBottom: 0,
	},
	inlineMapWrap: {
		flex: 1,
		borderRadius: 0,
		overflow: "hidden",
		borderWidth: 0,
		borderColor: colors.borderLight || colors.border,
		backgroundColor: colors.card,
		...shadows.small,
		position: "relative",
	},
	inlineMapView: {
		flex: 1,
		backgroundColor: colors.background,
	},
	inlineMapEmpty: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: spacing.lg,
		gap: spacing.sm,
	},
	inlineMapEmptyText: {
		...typography.caption,
		color: colors.textSecondary,
		textAlign: "center",
		writingDirection: "rtl",
	},
	inlineMapEmptyTitle: {
		...typography.h4,
		color: colors.textPrimary,
		textAlign: "center",
		writingDirection: "rtl",
	},
	mapControls: {
		position: "absolute",
		right: 14,
		zIndex: 60,
	},
	mapControlButton: {
		width: 48,
		height: 48,
		borderRadius: 24,
		backgroundColor: "rgba(255,255,255,0.96)",
		borderWidth: 1,
		borderColor: "rgba(30,58,95,0.12)",
		alignItems: "center",
		justifyContent: "center",
		...shadows.small,
	},
	mapSearchAreaButton: {
		position: "absolute",
		top: 14,
		alignSelf: "center",
		minHeight: 42,
		borderRadius: 21,
		backgroundColor: colors.primary,
		paddingHorizontal: 17,
		flexDirection: "row-reverse",
		alignItems: "center",
		justifyContent: "center",
		gap: 7,
		zIndex: 70,
		...shadows.small,
	},
	mapSearchAreaText: {
		color: colors.white,
		fontSize: 14,
		fontFamily: fontFamilies.semiBold,
		writingDirection: "rtl",
	},
	mapLocationNotice: {
		position: "absolute",
		left: 42,
		right: 42,
		bottom: 24,
		minHeight: 42,
		borderRadius: 16,
		backgroundColor: "rgba(255,255,255,0.96)",
		borderWidth: 1,
		borderColor: "rgba(30,58,95,0.12)",
		paddingHorizontal: 12,
		flexDirection: "row-reverse",
		alignItems: "center",
		justifyContent: "center",
		gap: 7,
		zIndex: 55,
	},
	mapLocationNoticeText: {
		flexShrink: 1,
		color: colors.textPrimary,
		fontSize: 12,
		fontFamily: fontFamilies.semiBold,
		textAlign: "right",
		writingDirection: "rtl",
	},
	mapLoadingPill: {
		position: "absolute",
		top: 66,
		alignSelf: "center",
		minHeight: 38,
		borderRadius: 19,
		backgroundColor: "rgba(255,255,255,0.96)",
		paddingHorizontal: 13,
		flexDirection: "row-reverse",
		alignItems: "center",
		gap: 8,
		zIndex: 65,
		...shadows.small,
	},
	mapLoadingText: {
		color: colors.textPrimary,
		fontSize: 12,
		fontFamily: fontFamilies.semiBold,
		writingDirection: "rtl",
	},
	mapErrorPill: {
		position: "absolute",
		top: 66,
		alignSelf: "center",
		minHeight: 40,
		borderRadius: 20,
		backgroundColor: "rgba(254,242,242,0.97)",
		borderWidth: 1,
		borderColor: "rgba(239,68,68,0.2)",
		paddingHorizontal: 14,
		flexDirection: "row-reverse",
		alignItems: "center",
		gap: 7,
		zIndex: 65,
	},
	mapErrorText: {
		color: "#991B1B",
		fontSize: 12,
		fontFamily: fontFamilies.semiBold,
		writingDirection: "rtl",
	},
	mapEmptyPill: {
		position: "absolute",
		top: 66,
		alignSelf: "center",
		minHeight: 38,
		borderRadius: 19,
		backgroundColor: "rgba(255,255,255,0.96)",
		paddingHorizontal: 14,
		justifyContent: "center",
		zIndex: 55,
	},
	mapEmptyPillText: {
		color: colors.textSecondary,
		fontSize: 12,
		fontFamily: fontFamilies.semiBold,
		writingDirection: "rtl",
	},
	mapZoomNotice: {
		position: "absolute",
		top: 66,
		left: 44,
		right: 44,
		minHeight: 40,
		borderRadius: 20,
		backgroundColor: "rgba(255,247,237,0.97)",
		borderWidth: 1,
		borderColor: "rgba(245,150,29,0.24)",
		paddingHorizontal: 13,
		alignItems: "center",
		justifyContent: "center",
		zIndex: 64,
	},
	mapZoomNoticeText: {
		color: "#9A4E08",
		fontSize: 12,
		fontFamily: fontFamilies.semiBold,
		textAlign: "center",
		writingDirection: "rtl",
	},
	// Rich recommendation preview
	mapPreviewCard: {
		position: "absolute",
		left: spacing.md,
		right: spacing.md,
		backgroundColor: colors.card,
		borderRadius: 22,
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.9)",
		padding: 12,
		shadowColor: colors.shadow,
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.22,
		shadowRadius: 20,
		elevation: 12,
		zIndex: 1000,
	},
	mapPreviewRow: {
		flexDirection: "row-reverse",
		alignItems: "stretch",
		gap: 12,
	},
	mapPreviewImage: {
		width: 96,
		height: 132,
		borderRadius: 16,
		backgroundColor: colors.borderLight,
	},
	mapPreviewImagePlaceholder: {
		width: 96,
		height: 132,
		borderRadius: 16,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: colors.surfaceSubtle,
	},
	mapPreviewContent: {
		flex: 1,
		minWidth: 0,
	},
	mapPreviewHeaderRow: {
		minHeight: 32,
		flexDirection: "row-reverse",
		alignItems: "center",
		justifyContent: "space-between",
		gap: spacing.sm,
	},
	mapPreviewCategory: {
		minHeight: 28,
		maxWidth: "75%",
		flexDirection: "row-reverse",
		alignItems: "center",
		gap: 5,
		borderRadius: 14,
		paddingHorizontal: 9,
		paddingVertical: 4,
		backgroundColor: "transparent",
	},
	mapPreviewCategoryText: {
		fontSize: 12,
		fontFamily: fontFamilies.semiBold,
		color: colors.textSecondary,
		textAlign: "right",
		writingDirection: "rtl",
	},
	mapPreviewCloseButton: {
		width: 44,
		height: 44,
		marginTop: -7,
		marginLeft: -7,
		borderRadius: 22,
		alignItems: "center",
		justifyContent: "center",
	},
	mapPreviewTitle: {
		...typography.h4,
		marginTop: 1,
		lineHeight: 21,
		flex: 1,
		textAlign: "right",
		writingDirection: "rtl",
		color: colors.textPrimary,
	},
	mapPreviewLocationRow: {
		marginTop: 3,
		flexDirection: "row-reverse",
		alignItems: "center",
		gap: 4,
	},
	mapPreviewLocationText: {
		...typography.caption,
		flex: 1,
		textAlign: "right",
		writingDirection: "rtl",
		color: colors.textSecondary,
	},
	mapPreviewMetaRow: {
		marginTop: 5,
		flexDirection: "row-reverse",
		alignItems: "center",
		flexWrap: "wrap",
		gap: 9,
	},
	mapPreviewMetaItem: {
		flexDirection: "row-reverse",
		alignItems: "center",
		gap: 3,
	},
	mapPreviewMetaText: {
		fontSize: 12,
		fontFamily: fontFamilies.semiBold,
		color: colors.textSecondary,
	},
	mapPreviewPrimaryButton: {
		minHeight: 44,
		marginTop: 7,
		borderRadius: 13,
		flexDirection: "row-reverse",
		alignItems: "center",
		justifyContent: "center",
		gap: 5,
		paddingHorizontal: spacing.md,
		backgroundColor: colors.primary,
	},
	mapPreviewPrimaryButtonText: {
		color: colors.white,
		fontSize: 14,
		fontFamily: fontFamilies.semiBold,
	},
};
