import { StyleSheet } from 'react-native';

import { colors } from './colors';
import { fontFamilies } from './typography';
import { layout, radii } from './designTokens';

export const commentStyles = StyleSheet.create({
  keyboard: { flex: 1 },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.52)',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  sheet: {
    width: '100%',
    maxWidth: 720,
    height: '92%',
    backgroundColor: colors.white,
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    overflow: 'hidden',
  },
  handle: {
    alignSelf: 'center',
    width: 48,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#D1D5DB',
    marginTop: 9,
    marginBottom: 5,
  },
  header: {
    minHeight: 56,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    paddingHorizontal: 12,
  },
  headerSide: {
    width: layout.touchTarget,
    height: layout.touchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    writingDirection: 'rtl',
    fontFamily: fontFamilies.semiBold,
    fontSize: 20,
    color: colors.textPrimary,
  },
  section: { flex: 1, backgroundColor: colors.white },
  notice: {
    marginHorizontal: 16,
    marginTop: 10,
    borderRadius: radii.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.warningLight,
  },
  noticeText: { color: colors.textSecondary, textAlign: 'right', writingDirection: 'rtl' },
  list: { flex: 1 },
  listContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 16 },
  listContentEmpty: { flexGrow: 1, justifyContent: 'center' },
  commentRow: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 9,
  },
  replyRow: { marginRight: 42, paddingVertical: 7 },
  highlighted: {
    backgroundColor: '#FFF7ED',
    borderRadius: radii.md,
    paddingHorizontal: 8,
  },
  commentBody: { flex: 1, minWidth: 0, alignItems: 'stretch' },
  metaRow: { flexDirection: 'row-reverse', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
  author: {
    fontFamily: fontFamilies.semiBold,
    fontSize: 14,
    color: colors.textPrimary,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  time: { fontSize: 12, color: colors.textMuted, textAlign: 'right' },
  edited: { fontSize: 11, color: colors.textMuted },
  replyingTo: {
    marginTop: 2,
    fontSize: 12,
    color: colors.primary,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  commentText: {
    marginTop: 3,
    fontSize: 15,
    lineHeight: 21,
    color: colors.textPrimary,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  actions: { flexDirection: 'row-reverse', alignItems: 'center', minHeight: 34, gap: 14 },
  actionButton: { minHeight: layout.touchTarget, justifyContent: 'center', paddingHorizontal: 2 },
  actionText: { fontFamily: fontFamilies.medium, fontSize: 13, color: colors.textSecondary },
  threadToggle: {
    alignSelf: 'flex-end',
    minHeight: layout.touchTarget,
    marginRight: 50,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  threadLine: { width: 28, height: StyleSheet.hairlineWidth, backgroundColor: colors.border },
  threadToggleText: { fontFamily: fontFamilies.medium, fontSize: 13, color: colors.textSecondary },
  loadMore: { alignSelf: 'center', minHeight: layout.touchTarget, justifyContent: 'center', paddingHorizontal: 18 },
  loadMoreText: { fontFamily: fontFamilies.medium, color: colors.primary, fontSize: 14 },
  centerState: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, gap: 10 },
  stateTitle: { fontFamily: fontFamilies.semiBold, fontSize: 17, color: colors.textPrimary, textAlign: 'center' },
  stateText: { fontSize: 14, color: colors.textSecondary, textAlign: 'center', writingDirection: 'rtl' },
  retry: { minHeight: layout.touchTarget, justifyContent: 'center', paddingHorizontal: 18 },
  retryText: { fontFamily: fontFamilies.medium, color: colors.primary },
  replyError: { marginRight: 50, color: colors.error, textAlign: 'right' },
  composerShell: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.white,
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  composerContext: {
    minHeight: 34,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 42,
  },
  composerContextText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 13,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  composerRow: { flexDirection: 'row-reverse', alignItems: 'flex-end', gap: 9 },
  inputWrap: {
    flex: 1,
    minHeight: layout.touchTarget,
    maxHeight: 108,
    flexDirection: 'row-reverse',
    alignItems: 'flex-end',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    paddingRight: 14,
    paddingLeft: 4,
  },
  input: {
    flex: 1,
    minHeight: 42,
    maxHeight: 96,
    paddingTop: 10,
    paddingBottom: 9,
    color: colors.textPrimary,
    fontSize: 15,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  send: {
    width: layout.touchTarget,
    height: layout.touchTarget,
    borderRadius: layout.touchTarget / 2,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendDisabled: { backgroundColor: '#CBD5E1' },
});
