import { StyleSheet } from 'react-native';
import { fontFamilies as fonts } from './typography';
import { navigationPalette } from './mainNavigationStyles';

export const communityPalette = { ...navigationPalette, ink: '#172C43', teal: '#087E91' };
const c = communityPalette;
const physical = { direction: 'ltr' };
export const COMMUNITY_HEADER_HEIGHT = 120;
export const COMMUNITY_MEDIA_RATIO = 16 / 10;

export const communityDiscoveryStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: c.sand },
  header: { paddingBottom: 12, borderBottomLeftRadius: 28, borderBottomRightRadius: 28 },
  headerContent: { paddingHorizontal: 16 },
  modeRow: { ...physical, flexDirection: 'row-reverse', alignItems: 'center', gap: 8, height: 44 },
  modeWrap: { flex: 1, minWidth: 0 },
  modes: { ...physical, flexDirection: 'row-reverse', gap: 4 },
  mode: { flex: 1, minHeight: 44, borderRadius: 20, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 4 },
  modeSelected: { backgroundColor: c.white },
  modeText: { color: c.white, fontSize: 16, lineHeight: 22, fontFamily: fonts.semiBold, writingDirection: 'rtl', flexShrink: 1 },
  selectedText: { color: c.navy },
  iconButton: { width: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 20 },
  mapButton: { backgroundColor: c.softBlue },
  whiteLabel: { fontSize: 14, lineHeight: 20, color: c.white, fontFamily: fonts.semiBold },
  mapLabel: { color: c.navy, fontSize: 12, fontFamily: fonts.semiBold },
  searchRow: { ...physical, flexDirection: 'row-reverse', alignItems: 'center', gap: 8, height: 48 },
  searchField: { flex: 1, minWidth: 0, height: 48, borderRadius: 20, paddingHorizontal: 12, backgroundColor: c.white, flexDirection: 'row-reverse', alignItems: 'center', gap: 4 },
  searchInput: { flex: 1, minWidth: 0, height: 48, padding: 0, fontSize: 16, fontFamily: fonts.regular, color: c.ink, textAlign: 'right', writingDirection: 'rtl' },
  searchOpen: { flex: 1, minWidth: 0, minHeight: 48, justifyContent: 'center' },
  searchLabel: { color: c.ink, fontSize: 16, lineHeight: 22, fontFamily: fonts.regular, writingDirection: 'rtl', textAlign: 'right' },
  searchPlaceholder: { color: c.muted },
  searchSheetInput: { ...physical, height: 48, flexDirection: 'row-reverse', gap: 8, alignItems: 'center', paddingHorizontal: 12, borderRadius: 10, backgroundColor: c.white },
  searchClear: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', marginLeft: -8 },
  filterBadge: { position: 'absolute', top: 0, right: 0, minWidth: 18, height: 18, borderRadius: 9, backgroundColor: c.orange, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 },
  filterBadgeText: { fontSize: 11, fontFamily: fonts.bold, color: c.navy },
  suggestionRow: { ...physical, minHeight: 68, flexDirection: 'row-reverse', alignItems: 'center', gap: 12, padding: 12, marginBottom: 12, borderRadius: 10, backgroundColor: c.white },
  freeTextAction: { minHeight: 44, borderRadius: 10, padding: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: c.softBlue },
  freeTextLabel: { maxWidth: '100%', textAlign: 'center', writingDirection: 'rtl' },
  suggestionCopy: { flex: 1, minWidth: 0 },
  suggestionTitle: { fontSize: 16, lineHeight: 22, fontFamily: fonts.semiBold, color: c.ink, textAlign: 'right', writingDirection: 'rtl' },
  suggestionHint: { fontSize: 14, lineHeight: 20, color: c.muted, textAlign: 'right', writingDirection: 'rtl' },
  notice: { color: c.navy, fontSize: 14, lineHeight: 20, textAlign: 'right', writingDirection: 'rtl', paddingVertical: 8 },
  activeRow: { ...physical, height: 44, flexDirection: 'row-reverse', alignItems: 'center', paddingHorizontal: 16, gap: 8, backgroundColor: c.sand },
  activeScroll: { flex: 1, minWidth: 0 },
  activeContent: { alignItems: 'center', gap: 8 },
  activeChip: { ...physical, flexDirection: 'row-reverse', minHeight: 44, alignItems: 'center', gap: 6, paddingHorizontal: 12, borderRadius: 20, backgroundColor: c.softBlue },
  activeLabel: { fontSize: 14, lineHeight: 20, fontFamily: fonts.semiBold, color: c.navy, maxWidth: 190 },
  clearFilters: { minHeight: 44, justifyContent: 'center' },
  feed: { paddingHorizontal: 16, paddingTop: 16, backgroundColor: c.sand },
  hiddenFeed: { display: 'none' },
  card: { width: '100%', backgroundColor: c.white, borderRadius: 20, overflow: 'hidden', marginBottom: 16 },
  cardBody: { minHeight: 176, paddingTop: 12, paddingHorizontal: 16, gap: 4 },
  cardTitle: { color: c.ink, fontSize: 20, lineHeight: 26, fontFamily: fonts.bold, textAlign: 'right', writingDirection: 'rtl' },
  cardDestination: { color: c.teal, fontSize: 14, lineHeight: 20, fontFamily: fonts.semiBold, textAlign: 'right', writingDirection: 'rtl' },
  destinationLink: { minHeight: 44, justifyContent: 'center' },
  cardMetadata: { color: c.muted, fontSize: 12, lineHeight: 18, textAlign: 'right', writingDirection: 'rtl' },
  cardExcerpt: { color: c.ink, fontSize: 16, lineHeight: 22, textAlign: 'right', writingDirection: 'rtl', paddingBottom: 4 },
  avatarRing: { width: 36, height: 36, borderRadius: 18, borderWidth: 0 },
  author: { minHeight: 44 },
  headerActions: { backgroundColor: 'transparent', borderRadius: 0, paddingHorizontal: 0, paddingVertical: 0, gap: 0 },
  favorite: { width: 44, height: 44, borderRadius: 10, backgroundColor: c.white },
  photoPosition: { position: 'absolute', bottom: 12, right: 12, minWidth: 44, height: 24, paddingHorizontal: 8, borderRadius: 10, backgroundColor: c.white, zIndex: 4, alignItems: 'center', justifyContent: 'center' },
  photoPositionText: { color: c.navy, fontSize: 12, lineHeight: 18, fontFamily: fonts.semiBold, writingDirection: 'ltr' },
  state: { flex: 1, minHeight: 240, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24, paddingVertical: 32, gap: 12 },
  stateTitle: { fontSize: 22, lineHeight: 28, fontFamily: fonts.bold, color: c.ink, textAlign: 'center', writingDirection: 'rtl' },
  stateText: { fontSize: 16, lineHeight: 22, color: c.muted, textAlign: 'center', writingDirection: 'rtl' },
  stateButton: { minHeight: 48, minWidth: 150, borderRadius: 10, backgroundColor: c.navy, paddingHorizontal: 20, alignItems: 'center', justifyContent: 'center' },
  stateButtonText: { fontSize: 16, lineHeight: 22, fontFamily: fonts.semiBold, color: c.white },
  secondaryAction: { minHeight: 44, paddingHorizontal: 16, justifyContent: 'center' },
  sheetOverlay: { justifyContent: 'flex-end', paddingHorizontal: 0, paddingVertical: 0 },
  // Fill the keyboard-adjusted overlay, rather than retaining a full-window height.
  sheet: { flex: 1, height: 'auto', width: '100%', maxWidth: 600, maxHeight: '100%', alignSelf: 'center', borderRadius: 0, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 0, paddingHorizontal: 0, paddingTop: 0, paddingBottom: 0, backgroundColor: c.sand },
  sheetHeader: { padding: 20, backgroundColor: c.white, borderTopLeftRadius: 28, borderTopRightRadius: 28, gap: 8 },
  sheetHeadingRow: { ...physical, flexDirection: 'row', alignItems: 'center', gap: 16 },
  sheetTitle: { flex: 1, textAlign: 'right', writingDirection: 'rtl', fontSize: 24, lineHeight: 30, fontFamily: fonts.bold, color: c.ink },
  sheetFooter: { paddingHorizontal: 20, paddingTop: 12, backgroundColor: c.white, gap: 8 },
  sheetContent: { padding: 20 },
  sortOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(13,23,36,0.32)' },
  sortBackdrop: { ...StyleSheet.absoluteFillObject },
  sortPanel: { width: '100%', maxWidth: 600, alignSelf: 'center', padding: 20, borderTopLeftRadius: 20, borderTopRightRadius: 20, gap: 12, backgroundColor: c.white },
  sortOption: { minHeight: 60, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 10, justifyContent: 'center' },
  sortSelected: { backgroundColor: c.softBlue },
  durationChoices: { flexDirection: 'row-reverse', gap: 8, marginBottom: 12 },
  durationChoice: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: c.softBlue },
  durationSelected: { backgroundColor: c.navy },
  filterHeading: { fontSize: 16, lineHeight: 22, fontFamily: fonts.bold, color: c.ink, textAlign: 'right', writingDirection: 'rtl', marginBottom: 8 },
  optionChip: { minHeight: 44, borderRadius: 10, backgroundColor: c.softBlue, borderColor: c.softBlue, paddingVertical: 8 },
  optionSelected: { backgroundColor: c.softOrange, borderColor: c.orange },
  optionText: { color: c.navy, fontSize: 14, lineHeight: 20 },
  optionSelectedText: { color: c.navy },
});
