import { StyleSheet } from 'react-native';

import { colors } from './colors';
import { fontFamilies } from './typography';

export const preferenceSetupStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F4F5F9' },
  screen: { flex: 1, backgroundColor: '#F4F5F9' },
  loadingState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { color: '#526174', textAlign: 'center', writingDirection: 'rtl' },

  heroScreen: { flex: 1, backgroundColor: '#F4F5F9', paddingHorizontal: 18, paddingBottom: 10 },
  heroImageWrap: {
    flex: 1.35,
    minHeight: 280,
    maxHeight: 460,
    marginTop: 8,
    overflow: 'hidden',
    borderRadius: 28,
    backgroundColor: '#DDE4EC',
  },
  heroImage: { width: '100%', height: '100%' },
  heroNameCard: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    minWidth: 170,
    paddingHorizontal: 15,
    paddingVertical: 11,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.94)',
  },
  heroName: { color: '#1E3A5F', fontSize: 20, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  heroRole: { marginTop: 2, color: '#526174', fontSize: 12, textAlign: 'right' },
  heroCopy: { flexShrink: 1, paddingHorizontal: 4, paddingTop: 20, paddingBottom: 12 },
  heroTitle: { color: '#17263A', fontSize: 28, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  heroText: { marginTop: 8, color: '#526174', fontSize: 16, lineHeight: 24, textAlign: 'right', writingDirection: 'rtl' },
  heroActions: { gap: 4 },

  questionHeader: {
    minHeight: 62,
    paddingHorizontal: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#DDE3EB',
  },
  brandText: { width: 82, color: '#1E3A5F', fontSize: 20, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  skipButton: { minWidth: 82, minHeight: 44, alignItems: 'flex-start', justifyContent: 'center' },
  skipText: { color: '#526174', fontSize: 14, fontFamily: fontFamilies.medium },
  progressDots: { flexDirection: 'row-reverse', alignItems: 'center', gap: 7 },
  progressDot: { width: 26, height: 5, borderRadius: 3, backgroundColor: '#D9E0E8' },
  progressDotActive: { backgroundColor: '#F5961D' },
  questionContent: { flexGrow: 1, paddingHorizontal: 18, paddingTop: 20, paddingBottom: 24 },
  noyaPrompt: { flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 11, marginBottom: 20 },
  noyaAvatar: { width: 54, height: 54, borderRadius: 27, borderWidth: 2, borderColor: '#FFFFFF' },
  noyaBubble: {
    flex: 1,
    minHeight: 70,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    shadowColor: '#1E3A5F',
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  noyaQuestion: { color: '#17263A', fontSize: 18, fontFamily: fontFamilies.semiBold, textAlign: 'right', writingDirection: 'rtl' },
  noyaHelper: { marginTop: 4, color: '#6F7E91', fontSize: 13, lineHeight: 19, textAlign: 'right', writingDirection: 'rtl' },
  choiceGrid: { flexDirection: 'row-reverse', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  choiceTile: {
    width: '48.4%',
    minHeight: 72,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
    borderWidth: 1,
    borderColor: '#D9E0E8',
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
  },
  choiceTileWide: { width: '100%' },
  choiceTileSelected: { borderColor: '#1E3A5F', backgroundColor: '#EAF0F7' },
  choiceTilePressed: { opacity: 0.82 },
  choiceIcon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EDF1F6' },
  choiceIconSelected: { backgroundColor: '#1E3A5F' },
  choiceLabel: { flex: 1, color: '#26374C', fontSize: 14, lineHeight: 19, fontFamily: fontFamilies.medium, textAlign: 'right', writingDirection: 'rtl' },
  choiceLabelSelected: { color: '#1E3A5F', fontFamily: fontFamilies.semiBold },
  selectionCounter: { marginTop: 11, color: '#1E3A5F', fontSize: 13, fontFamily: fontFamilies.medium, textAlign: 'right' },
  optionalCard: { marginTop: 16, borderRadius: 17, backgroundColor: '#FFFFFF', overflow: 'hidden' },
  optionalHeader: { minHeight: 72, paddingHorizontal: 15, paddingVertical: 12, flexDirection: 'row-reverse', alignItems: 'center', gap: 12 },
  optionalCopy: { flex: 1 },
  optionalTitle: { color: '#26374C', fontSize: 15, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  optionalText: { marginTop: 3, color: '#748296', fontSize: 12, textAlign: 'right' },
  needChoices: { paddingHorizontal: 12, paddingBottom: 14, flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8 },
  needChip: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 13, borderWidth: 1, borderColor: '#D9E0E8', borderRadius: 22, backgroundColor: '#FFFFFF' },
  needChipSelected: { borderColor: '#1E3A5F', backgroundColor: '#1E3A5F' },
  needChipText: { color: '#34465C', fontSize: 13, textAlign: 'center' },
  needChipTextSelected: { color: '#FFFFFF', fontFamily: fontFamilies.medium },
  footer: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 8, gap: 3, backgroundColor: '#FFFFFF', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#DDE3EB' },
  primaryButton: { minHeight: 52, borderRadius: 16, backgroundColor: '#1E3A5F', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  primaryButtonDisabled: { opacity: 0.45 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 16, fontFamily: fontFamilies.semiBold, textAlign: 'center' },
  textButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  textButtonText: { color: '#526174', fontSize: 14, fontFamily: fontFamilies.medium },

  finishScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingVertical: 20, backgroundColor: '#F4F5F9' },
  finishAvatar: { width: 118, height: 118, borderRadius: 59, borderWidth: 4, borderColor: '#FFFFFF' },
  finishTitle: { marginTop: 20, color: '#17263A', fontSize: 25, fontFamily: fontFamilies.semiBold, textAlign: 'center' },
  finishText: { maxWidth: 330, marginTop: 8, color: '#59687B', fontSize: 15, lineHeight: 23, textAlign: 'center', writingDirection: 'rtl' },
  previewRow: { width: '100%', minHeight: 128, marginTop: 20, flexDirection: 'row-reverse', justifyContent: 'center', gap: 9 },
  previewCard: { width: '31%', minHeight: 126, overflow: 'hidden', borderRadius: 15, backgroundColor: '#FFFFFF' },
  previewImage: { width: '100%', height: 78 },
  previewFallback: { width: '100%', height: 78, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E6EAF0' },
  previewTitle: { paddingHorizontal: 8, paddingVertical: 7, color: '#26374C', fontSize: 12, lineHeight: 16, fontFamily: fontFamilies.medium, textAlign: 'right' },
  previewSkeleton: { width: '31%', height: 126, borderRadius: 15, backgroundColor: '#E2E7ED' },
  previewEmpty: {
    width: '100%', minHeight: 108, alignItems: 'center', justifyContent: 'center', gap: 8,
    paddingHorizontal: 20, borderRadius: 16, backgroundColor: '#FFFFFF',
  },
  previewEmptyText: { color: '#526174', fontSize: 14, lineHeight: 20, textAlign: 'center', writingDirection: 'rtl' },
  finishActions: { width: '100%', marginTop: 18, gap: 3 },

  promptCard: { marginHorizontal: 16, marginTop: 16, padding: 16, borderRadius: 18, backgroundColor: '#EAF2FF' },
  promptRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12 },
  promptAvatar: { width: 52, height: 52, borderRadius: 26, borderWidth: 2, borderColor: '#FFFFFF' },
  promptCopy: { flex: 1 },
  promptTitle: { color: colors.primary, fontSize: 16, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  promptText: { color: colors.textSecondary, fontSize: 13, lineHeight: 20, textAlign: 'right', marginTop: 5 },
  promptButton: { alignSelf: 'flex-end', minHeight: 44, justifyContent: 'center', marginTop: 12, paddingHorizontal: 14, borderRadius: 12, backgroundColor: colors.primary },
  promptButtonText: { color: '#FFFFFF', fontFamily: fontFamilies.medium },
  promptActions: { flexDirection: 'row-reverse', alignItems: 'center', gap: 10 },
  promptSecondaryButton: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 10, marginTop: 12 },
  promptSecondaryText: { color: colors.textSecondary, fontFamily: fontFamilies.medium },
  homeTipWrap: { marginHorizontal: 16, marginTop: 14 },
  editSectionCard: { marginTop: 18 },
  editSectionHelp: { textAlign: 'right', color: colors.textSecondary, marginTop: 5 },
  editChipRow: { marginTop: 10 },
});
