import { fontFamilies } from "./typography";
import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const preferenceSetupStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 16,
    backgroundColor: colors.primary,
  },
  headerRow: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between' },
  closeButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  closePlaceholder: { width: 40 },
  headerTitle: { color: '#FFFFFF', fontSize: 22, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  headerSubtitle: { color: 'rgba(255,255,255,0.82)', fontSize: 14, textAlign: 'right', marginTop: 6 },
  progressTrack: { height: 5, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.24)', marginTop: 16 },
  progressFill: { height: 5, borderRadius: 3, backgroundColor: '#FFFFFF' },
  content: { padding: 20, paddingBottom: 130 },
  brandSurface: { backgroundColor: '#FFFFFF', borderRadius: 20, alignItems: 'center', paddingTop: 16, marginBottom: 20 },
  sectionTitle: { color: colors.textPrimary, fontSize: 22, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  sectionHelp: { color: colors.textSecondary, fontSize: 14, lineHeight: 21, textAlign: 'right', marginTop: 6 },
  counter: { color: colors.primary, fontSize: 13, fontFamily: fontFamilies.medium, textAlign: 'right', marginTop: 8 },
  chipWrap: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 10, marginTop: 18 },
  chip: {
    borderWidth: 1,
    borderColor: '#D9DFEA',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 22,
  },
  chipSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { color: colors.textPrimary, fontSize: 14, textAlign: 'right' },
  chipTextSelected: { color: '#FFFFFF', fontFamily: fontFamilies.medium },
  optionGroup: { marginTop: 24 },
  optionTitle: { color: colors.textPrimary, fontSize: 17, fontFamily: fontFamilies.medium, textAlign: 'right' },
  optionHelp: { color: colors.textMuted, fontSize: 12, textAlign: 'right', marginTop: 4 },
  privacyCard: { backgroundColor: '#EAF2FF', borderRadius: 16, padding: 16, marginTop: 24 },
  privacyTitle: { color: colors.primary, fontFamily: fontFamilies.medium, fontSize: 15, textAlign: 'right' },
  privacyText: { color: colors.textSecondary, fontSize: 13, lineHeight: 20, textAlign: 'right', marginTop: 6 },
  footer: {
    position: 'absolute', left: 0, right: 0, bottom: 0,
    flexDirection: 'row-reverse', gap: 12, padding: 16,
    backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E8ECF3',
  },
  primaryButton: { flex: 1, borderRadius: 14, backgroundColor: colors.primary, paddingVertical: 15, alignItems: 'center' },
  primaryButtonDisabled: { opacity: 0.55 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 16, fontFamily: fontFamilies.medium },
  secondaryButton: { borderRadius: 14, borderWidth: 1, borderColor: '#D9DFEA', paddingHorizontal: 22, paddingVertical: 15 },
  secondaryButtonText: { color: colors.textPrimary, fontSize: 16, fontFamily: fontFamilies.medium },
  promptCard: { marginHorizontal: 16, marginTop: 16, padding: 16, borderRadius: 18, backgroundColor: '#EAF2FF' },
  promptTitle: { color: colors.primary, fontSize: 16, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  promptText: { color: colors.textSecondary, fontSize: 13, lineHeight: 20, textAlign: 'right', marginTop: 5 },
  promptButton: { alignSelf: 'flex-end', marginTop: 12, paddingHorizontal: 14, paddingVertical: 9, borderRadius: 12, backgroundColor: colors.primary },
  promptButtonText: { color: '#FFFFFF', fontFamily: fontFamilies.medium },
  editSectionCard: { marginTop: 18 },
  editSectionHelp: { textAlign: 'right', color: colors.textSecondary, marginTop: 5 },
  editChipRow: { marginTop: 10 },
});
