import { StyleSheet } from 'react-native';

import { colors } from './colors';
import { fontFamilies } from './typography';
import { shadows } from './shadows';
import { spacing } from './spacing';

export const recommendationComposerStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.appSurface,
  },
  keyboardAvoiding: { flex: 1 },
  draftStateScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    backgroundColor: colors.appSurface,
  },
  draftCard: {
    width: '100%',
    maxWidth: 560,
    backgroundColor: colors.white,
    borderRadius: spacing.radiusLarge,
    padding: spacing.xl,
    gap: spacing.md,
    ...shadows.small,
  },
  draftTitle: { color: colors.primary, fontSize: 21, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  draftBody: { color: colors.textSecondary, fontSize: 15, lineHeight: 22, textAlign: 'right' },
  draftPrimaryButton: { flex: 0, width: '100%' },
  draftSecondaryButton: {
    minHeight: 50,
    borderRadius: spacing.radiusMedium,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  draftSecondaryText: { color: colors.primary, fontFamily: fontFamilies.medium },
  draftDestructiveText: { color: colors.error, fontFamily: fontFamilies.medium },
  header: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
  },
  headerTopRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    color: colors.white,
    fontSize: 20,
    fontFamily: fontFamilies.semiBold,
    writingDirection: 'rtl',
    textAlign: 'right',
  },
  headerSubtitle: { color: '#DCE8F6', fontSize: 13, lineHeight: 19, marginTop: spacing.xs, textAlign: 'right', writingDirection: 'rtl' },
  closeButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressCopy: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  progressText: {
    color: '#DCE8F6',
    fontSize: 12,
    writingDirection: 'rtl',
  },
  progressTrack: {
    height: 5,
    borderRadius: spacing.radiusFull,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginTop: spacing.sm,
    overflow: 'hidden',
    flexDirection: 'row-reverse',
  },
  progressFill: {
    height: '100%',
    borderRadius: spacing.radiusFull,
    backgroundColor: colors.accentAction,
  },
  saveStatusRow: { minHeight: 22, marginTop: spacing.sm, flexDirection: 'row-reverse', alignItems: 'center', gap: spacing.xs },
  saveStatusText: { color: '#DCE8F6', fontSize: 12 },
  saveRetryText: { color: colors.white, fontFamily: fontFamilies.medium, fontSize: 12, textDecorationLine: 'underline' },
  missingMediaNotice: { backgroundColor: colors.warningLight, borderRadius: spacing.radiusMedium, padding: spacing.md, marginBottom: spacing.md },
  missingMediaText: { color: colors.textPrimary, textAlign: 'right', lineHeight: 20 },
  scroll: { flex: 1 },
  content: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    gap: spacing.md,
  },
  sectionCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: spacing.radiusLarge,
    padding: spacing.lg,
    ...shadows.small,
  },
  sectionHeader: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.md },
  sectionTitle: { color: colors.textPrimary, fontSize: 18, fontFamily: fontFamilies.semiBold, textAlign: 'right', writingDirection: 'rtl' },
  sectionRequired: { color: colors.primary, fontSize: 12, fontFamily: fontFamilies.medium, backgroundColor: colors.accentLight, borderRadius: spacing.radiusFull, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  sectionDivider: { height: 1, backgroundColor: colors.borderLight, marginVertical: spacing.xl },
  noyaRow: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: spacing.sm,
    marginBottom: spacing.xl,
  },
  noyaAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 3,
    borderColor: colors.white,
    ...shadows.small,
  },
  noyaBubble: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: spacing.radiusLarge,
    borderTopRightRadius: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    ...shadows.small,
  },
  noyaClose: {
    position: 'absolute',
    left: spacing.sm,
    top: spacing.xs,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noyaCloseText: { color: colors.textMuted, fontSize: 22, lineHeight: 24 },
  noyaName: {
    color: colors.primary,
    fontSize: 12,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  noyaMessage: {
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 22,
    marginTop: spacing.xs,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  fieldLabel: {
    color: colors.textPrimary,
    fontSize: 14,
    fontFamily: fontFamilies.medium,
    marginBottom: spacing.sm,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  fieldHint: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: spacing.sm,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  fieldError: {
    color: colors.error,
    fontSize: 12,
    fontFamily: fontFamilies.medium,
    marginTop: spacing.sm,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  modeActions: {
    flexDirection: 'row-reverse',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  modeButton: {
    flex: 1,
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.radiusMedium,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row-reverse',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  modeButtonSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.accentLight,
  },
  modeButtonText: {
    color: colors.primary,
    fontSize: 13,
    fontFamily: fontFamilies.medium,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  locationPanel: {
    marginTop: spacing.lg,
  },
  confirmedLocation: { marginTop: spacing.md, borderWidth: 1, borderColor: colors.success, borderRadius: spacing.radiusLarge, overflow: 'hidden', backgroundColor: colors.white },
  confirmedLocationCopy: { padding: spacing.md, alignItems: 'flex-end' },
  confirmedLocationTitleRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: spacing.xs },
  confirmedLocationTitle: { flex: 1, color: colors.textPrimary, fontSize: 15, fontFamily: fontFamilies.semiBold, textAlign: 'right', writingDirection: 'auto' },
  confirmedLocationAddress: { color: colors.textSecondary, fontSize: 12, marginTop: spacing.xs, textAlign: 'right', writingDirection: 'auto' },
  locationAdjustButton: { minHeight: 44, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: spacing.xs, borderTopWidth: 1, borderTopColor: colors.borderLight, backgroundColor: colors.accentLight },
  selectedDestination: {
    minHeight: 68,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.successLight,
    borderRadius: spacing.radiusMedium,
  },
  selectedDestinationIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedDestinationCopy: { flex: 1, alignItems: 'flex-end' },
  selectedDestinationTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamilies.semiBold,
    fontSize: 15,
    textAlign: 'right',
  },
  selectedDestinationSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: spacing.xs,
    textAlign: 'right',
  },
  textAction: {
    color: colors.primary,
    fontFamily: fontFamilies.medium,
    fontSize: 13,
  },
  destinationPicker: { position: 'relative', zIndex: 10 },
  searchInputWrap: {
    minHeight: 50,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.radiusMedium,
    backgroundColor: colors.white,
  },
  searchInput: {
    flex: 1,
    minHeight: 48,
    color: colors.textPrimary,
    fontSize: 16,
    writingDirection: 'rtl',
  },
  destinationResults: {
    marginTop: spacing.sm,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.radiusMedium,
    overflow: 'hidden',
    ...shadows.small,
  },
  destinationResult: {
    minHeight: 58,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  destinationResultCopy: { flex: 1, alignItems: 'flex-end' },
  destinationResultTitle: { color: colors.textPrimary, fontFamily: fontFamilies.medium },
  destinationResultSubtitle: { color: colors.textSecondary, fontSize: 12, marginTop: 2 },
  destinationEmpty: { color: colors.textSecondary, padding: spacing.md, textAlign: 'right' },
  manualMap: {
    width: '100%',
    height: 260,
    borderRadius: spacing.radiusLarge,
    overflow: 'hidden',
    backgroundColor: colors.surfaceSubtle,
  },
  webMapPickerShell: { position: 'relative', width: '100%' },
  webMapLoading: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceSubtle,
    borderRadius: spacing.radiusLarge,
  },
  coordinateFields: {
    flexDirection: 'row-reverse',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  categoryGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  categoryTile: {
    flexBasis: '47%',
    flexGrow: 1,
    minHeight: 76,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.radiusMedium,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    padding: spacing.sm,
  },
  categoryTileSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.accentLight,
  },
  categoryTileText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontFamily: fontFamilies.medium,
    textAlign: 'center',
    writingDirection: 'rtl',
  },
  categoryTileTextSelected: { color: colors.primary },
  taxonomyHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  taxonomyTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
  },
  suggestionPanel: {
    backgroundColor: colors.secondaryLight,
    borderRadius: spacing.radiusMedium,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  suggestionText: {
    color: colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  suggestionActions: {
    flexDirection: 'row-reverse',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  chipWrap: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  chip: {
    minHeight: 42,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: spacing.radiusFull,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipSelected: { borderColor: colors.primary, backgroundColor: colors.primary },
  chipText: { color: colors.textPrimary, fontSize: 13, fontFamily: fontFamilies.medium },
  chipTextSelected: { color: colors.white },
  moreButton: {
    minHeight: 44,
    alignSelf: 'flex-end',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.sm,
  },
  moreText: { color: colors.primary, fontFamily: fontFamilies.medium, fontSize: 13 },
  allSubcategories: { marginTop: spacing.md },
  fieldStack: { gap: spacing.md },
  photoHint: { marginTop: -spacing.sm, marginBottom: spacing.sm },
  preview: {
    backgroundColor: colors.white,
    borderRadius: spacing.radiusLarge,
    overflow: 'hidden',
    ...shadows.small,
  },
  previewImage: { width: '100%', aspectRatio: 1, backgroundColor: colors.surfaceSubtle },
  previewPlaceholder: {
    width: '100%',
    height: 140,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewCopy: { padding: spacing.md, alignItems: 'flex-end' },
  previewTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
  },
  previewMeta: { color: colors.textSecondary, fontSize: 12, marginTop: spacing.xs, textAlign: 'right' },
  optionalTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontFamily: fontFamilies.semiBold,
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
    textAlign: 'right',
  },
  optionalField: { marginTop: spacing.md },
  ltrInput: { textAlign: 'left', writingDirection: 'ltr' },
  footerKeyboardAvoiding: { width: '100%' },
  footer: {
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    ...shadows.medium,
  },
  footerInner: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.sm,
  },
  primaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: spacing.radiusMedium,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonDisabled: { opacity: 0.5 },
  primaryButtonText: { color: colors.white, fontSize: 16, fontFamily: fontFamilies.medium },
  backButton: {
    minWidth: 60,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: { color: colors.primary, fontSize: 14, fontFamily: fontFamilies.medium },
  keyboardDismissButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.accentLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
