import { StyleSheet } from 'react-native';

import { colors } from './colors';
import { fontFamilies } from './typography';

export const routeBuilderStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.appSurface },
  content: { padding: 16, paddingBottom: 132, gap: 16 },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { color: colors.textSecondary, textAlign: 'center' },
  card: {
    backgroundColor: colors.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 14,
  },
  startTitle: { color: colors.primary, fontSize: 21, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  body: { color: colors.textSecondary, fontSize: 15, lineHeight: 22, textAlign: 'right' },
  fieldLabel: { color: colors.textPrimary, fontSize: 15, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  dayChoices: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8 },
  dayChoice: {
    minWidth: 60,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  dayChoiceSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
  dayChoiceText: { color: colors.primary, fontFamily: fontFamilies.semiBold },
  dayChoiceTextSelected: { color: colors.white },
  primaryButton: {
    minHeight: 50,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  primaryButtonDisabled: { opacity: 0.55 },
  primaryButtonText: { color: colors.white, fontSize: 16, fontFamily: fontFamilies.semiBold },
  secondaryButton: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  secondaryButtonText: { color: colors.primary, fontFamily: fontFamilies.semiBold },
  destructiveText: { color: colors.error, fontFamily: fontFamilies.semiBold },
  rowActions: { flexDirection: 'row-reverse', gap: 10 },
  rowButton: { flex: 1 },
  statusRow: { minHeight: 24, flexDirection: 'row-reverse', alignItems: 'center', gap: 7 },
  statusText: { color: colors.textMuted, fontSize: 13 },
  statusError: { color: colors.error },
  retryText: { color: colors.primary, fontSize: 13, fontFamily: fontFamilies.semiBold },
  mapPeek: {
    minHeight: 78,
    borderRadius: 18,
    backgroundColor: colors.primary,
    padding: 15,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mapPeekTitle: { color: colors.white, fontSize: 16, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  mapPeekMeta: { color: '#DCE6F2', marginTop: 4, textAlign: 'right' },
  tabs: { flexGrow: 0 },
  tabsContent: { flexDirection: 'row-reverse', gap: 8, paddingVertical: 2 },
  tab: {
    minHeight: 42,
    minWidth: 76,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  tabSelected: { backgroundColor: '#FFF3E2', borderColor: colors.brandOrange },
  tabText: { color: colors.textSecondary, fontFamily: fontFamilies.semiBold },
  tabTextSelected: { color: colors.primary },
  sectionHeader: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between' },
  sectionTitle: { color: colors.textPrimary, fontSize: 18, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  sectionMeta: { color: colors.textMuted, fontSize: 13 },
  empty: { color: colors.textMuted, textAlign: 'center', paddingVertical: 18, lineHeight: 21 },
  reorderHint: { color: colors.textMuted, fontSize: 12, textAlign: 'right' },
  stopCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
    borderRadius: 15,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
  },
  stopCardDragging: {
    borderColor: colors.brandOrange,
    backgroundColor: '#FFF9F0',
  },
  stopNumber: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopThumb: {
    width: 42,
    height: 42,
    borderRadius: 11,
    backgroundColor: colors.borderLight,
  },
  stopNumberText: { color: colors.white, fontFamily: fontFamilies.semiBold },
  stopCopy: { flex: 1, alignItems: 'flex-end' },
  stopTitle: { color: colors.textPrimary, fontFamily: fontFamilies.semiBold, textAlign: 'right' },
  stopMeta: { color: colors.textMuted, fontSize: 12, marginTop: 3, textAlign: 'right' },
  stopAction: { minWidth: 40, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  dragHandle: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  insertStop: {
    minHeight: 38,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  insertStopText: { color: colors.brandOrange, fontSize: 12, fontFamily: fontFamilies.semiBold },
  addStop: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.brandOrange,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addStopText: { color: colors.brandOrange, fontFamily: fontFamilies.semiBold },
  detailsToggle: {
    minHeight: 50,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 15,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
  },
  detailsToggleText: { color: colors.primary, fontFamily: fontFamilies.semiBold },
  optionalBox: { gap: 14, paddingTop: 4 },
  errorBox: { backgroundColor: colors.errorLight, borderRadius: 13, padding: 12 },
  errorText: { color: colors.error, textAlign: 'right' },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    padding: 14,
  },
});
