import { StyleSheet } from 'react-native';

import { colors } from './colors';
import { fontFamilies } from './typography';

const navy = colors.primary;
const orange = colors.accentAction;

export const tripPlannerStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#EDF1F4' },
  editorScreen: { flex: 1, backgroundColor: '#FAF7F2' },
  editorHeader: { backgroundColor: '#FFFFFF', paddingHorizontal: 16, paddingBottom: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E4E4DF' },
  editorBody: { flex: 1, backgroundColor: '#FFFFFF' },
  editorMapCard: { height: 142, marginHorizontal: 16, marginTop: 12, marginBottom: 12, borderRadius: 20, overflow: 'hidden', backgroundColor: '#EDF2F6' },
  editorMapOverlay: { position: 'absolute', bottom: 10, left: 10, borderRadius: 14, backgroundColor: '#FFFFFF', paddingHorizontal: 12, minHeight: 44, flexDirection: 'row-reverse', alignItems: 'center', gap: 6 },
  editorMapHint: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 5, paddingHorizontal: 20 },
  editorMapLoadingOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 2, backgroundColor: 'rgba(237,242,246,0.82)' },
  editorMapFailureBanner: { position: 'absolute', zIndex: 2, left: 8, right: 8, bottom: 8, minHeight: 48, borderRadius: 14, paddingHorizontal: 10, backgroundColor: 'rgba(255,255,255,0.96)', flexDirection: 'row-reverse', alignItems: 'center', gap: 8, shadowColor: '#102A43', shadowOpacity: 0.12, shadowRadius: 8, elevation: 3 },
  mapFullFailureBanner: { top: 88, bottom: undefined },
  editorMapFailureText: { flex: 1, color: navy, fontSize: 12, textAlign: 'right', writingDirection: 'rtl' },
  editorMapRetry: { minHeight: 40, borderRadius: 12, borderWidth: 1, borderColor: '#D9E0E5', paddingHorizontal: 10, backgroundColor: '#FFFFFF', flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 5 },
  editorMapHintText: { color: navy, fontSize: 13, textAlign: 'center', writingDirection: 'rtl' },
  editorFooter: { backgroundColor: '#FFFFFF', paddingHorizontal: 16, paddingTop: 10, flexDirection: 'row-reverse', gap: 8, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#E4E4DF' },
  editorAction: { flex: 1, minHeight: 52, borderRadius: 17, flexDirection: 'row-reverse', gap: 6, alignItems: 'center', justifyContent: 'center', backgroundColor: navy },
  editorActionPrimary: { backgroundColor: orange },
  editorActionText: { color: '#FFFFFF', fontSize: 14, fontFamily: fontFamilies.semiBold, writingDirection: 'rtl' },
  editorStatus: { minHeight: 27, color: '#647184', fontSize: 12, textAlign: 'right', writingDirection: 'rtl' },
  mapFullScreen: { flex: 1, backgroundColor: '#EDF2F6' },
  mapFullHeader: { position: 'absolute', zIndex: 3, top: 0, left: 0, right: 0, paddingHorizontal: 16, backgroundColor: '#FFFFFF' },
  mapFullDetails: { position: 'absolute', zIndex: 3, bottom: 14, left: 16, right: 16, borderRadius: 18, padding: 14, backgroundColor: '#FFFFFF' },
  resumeCard: { borderRadius: 18, minHeight: 72, backgroundColor: '#EDF2F6', flexDirection: 'row-reverse', alignItems: 'center', gap: 12, padding: 14 },
  resumeLink: { color: orange, fontFamily: fontFamilies.semiBold, fontSize: 14, writingDirection: 'rtl' },
  stopDetails: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#E4E4DF', paddingTop: 10, gap: 8 },
  stopDetailActions: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8 },
  stopDetailButton: { minHeight: 44, borderRadius: 14, borderWidth: 1, borderColor: '#E4E4DF', backgroundColor: '#FAF7F2', paddingHorizontal: 10, flexDirection: 'row-reverse', gap: 5, alignItems: 'center', justifyContent: 'center' },
  stopDetailText: { color: navy, fontSize: 12, fontFamily: fontFamilies.semiBold, writingDirection: 'rtl' },
  pickerTabs: { flexDirection: 'row-reverse', gap: 8, paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#FFFFFF' },
  pickerTab: { flex: 1, minHeight: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EDF2F6' },
  pickerTabActive: { backgroundColor: navy },
  pickerTabText: { color: navy, fontSize: 13, fontFamily: fontFamilies.semiBold, writingDirection: 'rtl' },
  pickerTabTextActive: { color: '#FFFFFF' },
  pickerDestinationRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8, paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#FFFFFF' },
  pickerTray: { backgroundColor: '#FFFFFF', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#E4E4DF', paddingHorizontal: 16, paddingTop: 10, gap: 8 },
  pickerPreview: { borderRadius: 18, borderWidth: 1, borderColor: '#E4E4DF', backgroundColor: '#FFFFFF', padding: 12, gap: 8 },
  map: { ...StyleSheet.absoluteFillObject },
  mapFallback: { ...StyleSheet.absoluteFillObject, backgroundColor: '#DDE7EC', overflow: 'hidden' },
  mapGridLine: { position: 'absolute', backgroundColor: 'rgba(30,58,95,0.08)' },
  webRouteLine: { position: 'absolute', height: 3, borderRadius: 2, backgroundColor: navy, opacity: 0.55 },
  webMapNote: { position: 'absolute', top: 134, alignSelf: 'center', backgroundColor: 'rgba(255,255,255,0.92)', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999 },
  webMapNoteText: { color: navy, fontSize: 12, writingDirection: 'rtl' },
  header: { position: 'absolute', top: 0, left: 0, right: 0, zIndex: 10, paddingHorizontal: 16, paddingBottom: 12, backgroundColor: 'rgba(255,255,255,0.96)', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: 'rgba(30,58,95,0.12)' },
  headerRow: { minHeight: 56, flexDirection: 'row-reverse', alignItems: 'center', gap: 8 },
  headerCopy: { flex: 1, alignItems: 'flex-end' },
  headerTitle: { width: '100%', color: '#102A43', fontSize: 20, lineHeight: 26, fontFamily: fontFamilies.bold, textAlign: 'right', writingDirection: 'rtl', paddingVertical: 4 },
  headerSubtitle: { color: '#5A6875', fontSize: 12, textAlign: 'right', writingDirection: 'rtl' },
  iconButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#F2F5F7', alignItems: 'center', justifyContent: 'center' },
  iconButtonPrimary: { backgroundColor: '#FFF0DE' },
  sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, zIndex: 20, backgroundColor: '#FFFFFF', borderTopLeftRadius: 28, borderTopRightRadius: 28, shadowColor: '#102A43', shadowOffset: { width: 0, height: -5 }, shadowOpacity: 0.16, shadowRadius: 18, elevation: 12, overflow: 'hidden' },
  sheetHandleArea: { height: 44, alignItems: 'center', justifyContent: 'center' },
  sheetHandle: { width: 44, height: 5, borderRadius: 999, backgroundColor: '#C7D0D8' },
  sheetContent: { flex: 1 },
  dayRail: { maxHeight: 56, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E5E9ED' },
  dayRailContent: { paddingHorizontal: 14, paddingBottom: 10, gap: 8, flexDirection: 'row-reverse', alignItems: 'center' },
  dayChip: { minWidth: 72, minHeight: 44, paddingHorizontal: 14, borderRadius: 22, borderWidth: 1, borderColor: '#D9E0E5', backgroundColor: '#F8FAFB', alignItems: 'center', justifyContent: 'center' },
  dayChipSelected: { backgroundColor: navy, borderColor: navy },
  dayChipText: { color: navy, fontSize: 13, fontFamily: fontFamilies.semiBold, textAlign: 'center', writingDirection: 'rtl' },
  dayChipTextSelected: { color: '#FFFFFF' },
  addDayChip: { width: 44, minWidth: 44, paddingHorizontal: 0, backgroundColor: '#FFF7ED', borderColor: '#F5C489' },
  summary: { minHeight: 52, paddingHorizontal: 16, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between' },
  summaryTitle: { color: '#102A43', fontSize: 16, fontFamily: fontFamilies.bold, textAlign: 'right', writingDirection: 'rtl' },
  summaryMeta: { color: '#6A7884', fontSize: 12, writingDirection: 'rtl' },
  modeToggle: { flexDirection: 'row-reverse', borderRadius: 18, backgroundColor: '#EEF2F5', padding: 3 },
  modeButton: { minWidth: 44, height: 36, borderRadius: 15, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 5, paddingHorizontal: 9 },
  modeButtonSelected: { backgroundColor: '#FFFFFF', shadowColor: '#102A43', shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  modeText: { color: '#647280', fontSize: 12 },
  modeTextSelected: { color: navy, fontFamily: fontFamilies.semiBold },
  list: { flex: 1, minHeight: 0 },
  listContent: { paddingHorizontal: 14, paddingBottom: 20, gap: 10 },
  stopRow: { minHeight: 82, gap: 10, borderWidth: 1, borderColor: '#E7EBEF', backgroundColor: '#FFFFFF', borderRadius: 18, padding: 10 },
  stopRowSelected: { borderColor: orange, backgroundColor: '#FFF9F1' },
  stopNumber: { width: 34, height: 34, borderRadius: 17, backgroundColor: navy, alignItems: 'center', justifyContent: 'center' },
  stopNumberCustom: { backgroundColor: orange },
  stopNumberText: { color: '#FFFFFF', fontSize: 13, fontFamily: fontFamilies.bold },
  stopCopy: { flex: 1, alignItems: 'flex-end' },
  stopTitle: { color: '#102A43', fontSize: 15, lineHeight: 20, fontFamily: fontFamilies.semiBold, textAlign: 'right', writingDirection: 'rtl' },
  stopSubtitle: { color: '#71808D', fontSize: 12, lineHeight: 17, textAlign: 'right', writingDirection: 'rtl' },
  stopSource: { marginTop: 3, color: orange, fontSize: 11, textAlign: 'right', writingDirection: 'rtl' },
  dragHandle: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  rowActions: { alignItems: 'center' },
  reorderButtons: { flexDirection: 'column', gap: 2 },
  reorderButton: { width: 32, height: 30, alignItems: 'center', justifyContent: 'center' },
  empty: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32, paddingTop: 24 },
  emptyIcon: { width: 64, height: 64, borderRadius: 32, backgroundColor: '#FFF0DE', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  emptyTitle: { color: '#102A43', fontSize: 18, fontFamily: fontFamilies.bold, textAlign: 'center', writingDirection: 'rtl' },
  emptyText: { color: '#667684', fontSize: 14, lineHeight: 21, textAlign: 'center', writingDirection: 'rtl', marginTop: 5 },
  composerBar: { position: 'absolute', left: 14, right: 14, bottom: 14, borderRadius: 22, backgroundColor: navy, flexDirection: 'row-reverse', padding: 6, gap: 6, shadowColor: '#102A43', shadowOpacity: 0.22, shadowRadius: 10, elevation: 8 },
  composerAction: { flex: 1, minHeight: 48, borderRadius: 17, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 7 },
  composerActionPrimary: { backgroundColor: orange },
  composerActionText: { color: '#FFFFFF', fontSize: 13, fontFamily: fontFamilies.semiBold, writingDirection: 'rtl' },
  banner: { position: 'absolute', top: 114, left: 16, right: 16, zIndex: 8, minHeight: 48, borderRadius: 16, backgroundColor: '#FFF7ED', borderWidth: 1, borderColor: '#FED7AA', paddingHorizontal: 13, paddingVertical: 10, flexDirection: 'row-reverse', alignItems: 'center', gap: 8 },
  bannerOffline: { backgroundColor: '#F3F4F6', borderColor: '#D1D5DB' },
  bannerText: { flex: 1, color: '#7C2D12', fontSize: 12, lineHeight: 17, textAlign: 'right', writingDirection: 'rtl' },
  loadingOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 40, backgroundColor: 'rgba(249,250,251,0.9)', alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { color: navy, fontSize: 14, writingDirection: 'rtl' },
  fullScreen: { flex: 1, backgroundColor: '#F4F6F8' },
  pageHeader: { flexDirection: 'row-reverse', minHeight: 64, paddingHorizontal: 16, alignItems: 'center', gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E1E7EB', backgroundColor: '#FFFFFF' },
  pageHeaderTitle: { flex: 1, color: '#102A43', fontSize: 22, fontFamily: fontFamilies.bold, textAlign: 'right', writingDirection: 'rtl' },
  pageContent: { padding: 16, paddingBottom: 42, gap: 14 },
  searchBox: { minHeight: 48, flexDirection: 'row-reverse', alignItems: 'center', gap: 8, paddingHorizontal: 14, borderWidth: 1, borderColor: '#D7DFE5', borderRadius: 16, backgroundColor: '#FFFFFF' },
  searchInput: { flex: 1, color: '#102A43', fontSize: 15, textAlign: 'right', writingDirection: 'rtl' },
  filterRow: { flexDirection: 'row-reverse', gap: 8, flexWrap: 'wrap' },
  filterChip: { minHeight: 44, paddingHorizontal: 14, borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D7DFE5', flexDirection: 'row-reverse', gap: 6, alignItems: 'center', justifyContent: 'center' },
  filterChipSelected: { backgroundColor: '#FFF0DE', borderColor: orange },
  filterText: { color: navy, fontSize: 13, writingDirection: 'rtl' },
  discoveryMap: { height: 220, borderRadius: 22, overflow: 'hidden', backgroundColor: '#DDE7EC' },
  discoveryList: { gap: 10 },
  discoveryCard: { minHeight: 82, flexDirection: 'row-reverse', alignItems: 'center', gap: 10, padding: 10, borderRadius: 18, borderWidth: 1, borderColor: '#E1E7EB', backgroundColor: '#FFFFFF' },
  discoveryCardSelected: { borderColor: orange, backgroundColor: '#FFF9F1' },
  discoveryThumb: { width: 62, height: 62, borderRadius: 14, backgroundColor: '#E9EEF2' },
  checkTouchTarget: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  check: { width: 28, height: 28, borderRadius: 14, borderWidth: 2, borderColor: '#B9C4CC', alignItems: 'center', justifyContent: 'center' },
  checkSelected: { backgroundColor: orange, borderColor: orange },
  selectionTray: { position: 'absolute', left: 12, right: 12, bottom: 12, minHeight: 72, borderRadius: 22, backgroundColor: navy, padding: 10, flexDirection: 'row-reverse', alignItems: 'center', gap: 10, shadowColor: '#102A43', shadowOpacity: 0.24, shadowRadius: 10, elevation: 10 },
  selectionCount: { flex: 1, color: '#FFFFFF', fontSize: 14, fontFamily: fontFamilies.semiBold, textAlign: 'right', writingDirection: 'rtl' },
  selectionButton: { minWidth: 126, minHeight: 48, borderRadius: 17, backgroundColor: orange, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  selectionButtonText: { color: '#FFFFFF', fontSize: 14, fontFamily: fontFamilies.bold, writingDirection: 'rtl' },
  formCard: { borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E1E7EB', padding: 16, gap: 12 },
  label: { color: '#102A43', fontSize: 14, fontFamily: fontFamilies.semiBold, textAlign: 'right', writingDirection: 'rtl' },
  input: { minHeight: 48, borderRadius: 15, borderWidth: 1, borderColor: '#D7DFE5', backgroundColor: '#FBFCFD', paddingHorizontal: 13, color: '#102A43', fontSize: 15, textAlign: 'right', writingDirection: 'rtl' },
  textarea: { minHeight: 92, paddingTop: 13, textAlignVertical: 'top' },
  primaryButton: { minHeight: 52, borderRadius: 17, backgroundColor: orange, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 8, paddingHorizontal: 18 },
  primaryButtonDisabled: { opacity: 0.48 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 15, fontFamily: fontFamilies.bold, writingDirection: 'rtl' },
  secondaryButton: { minHeight: 48, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D5DEE5', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  secondaryButtonText: { color: navy, fontSize: 14, fontFamily: fontFamilies.semiBold, writingDirection: 'rtl' },
  tripCard: { borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E3E8EC', padding: 16, gap: 10 },
  tripCardHeader: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12 },
  tripCardIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#FFF0DE', alignItems: 'center', justifyContent: 'center' },
  tripCardCopy: { flex: 1, alignItems: 'flex-end' },
  tripCardTitle: { color: '#102A43', fontSize: 17, fontFamily: fontFamilies.bold, textAlign: 'right', writingDirection: 'rtl' },
  tripCardMeta: { color: '#6A7884', fontSize: 13, textAlign: 'right', writingDirection: 'rtl' },
  tripCardFooter: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between' },
  deleteButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF1F2' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(10,34,56,0.42)', justifyContent: 'flex-end' },
  modalSheet: { maxHeight: '82%', backgroundColor: '#FFFFFF', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 16, paddingBottom: 28, gap: 12 },
  modalTitle: { color: '#102A43', fontSize: 20, fontFamily: fontFamilies.bold, textAlign: 'right', writingDirection: 'rtl' },
  modalText: { color: '#657582', fontSize: 14, lineHeight: 20, textAlign: 'right', writingDirection: 'rtl' },
  shareLink: { minHeight: 50, borderRadius: 15, backgroundColor: '#F4F6F8', padding: 12, justifyContent: 'center' },
  shareLinkText: { color: navy, fontSize: 12, textAlign: 'left' },
  conflictCard: { borderRadius: 18, backgroundColor: '#FFF7ED', borderWidth: 1, borderColor: '#FED7AA', padding: 14, gap: 10 },
  errorText: { color: '#B42318', fontSize: 13, textAlign: 'right', writingDirection: 'rtl' },
  readOnlyBadge: { alignSelf: 'flex-end', borderRadius: 999, backgroundColor: '#E8EEF4', paddingHorizontal: 12, paddingVertical: 7 },
  readOnlyText: { color: navy, fontSize: 12, fontFamily: fontFamilies.semiBold, writingDirection: 'rtl' },
});
