import { Platform, StyleSheet } from 'react-native';

import { colors } from './colors';
import { layout, radii } from './designTokens';
import { fontFamilies } from './typography';

const softShadow = Platform.select({
  web: { boxShadow: '0 8px 24px rgba(15,23,42,0.07)' },
  default: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 3,
  },
});

export const userDrawerStyles = StyleSheet.create({
  drawerSurface: {
    backgroundColor: '#F7F8FB',
    borderTopLeftRadius: radii.xl,
    borderBottomLeftRadius: radii.xl,
    overflow: 'hidden',
  },
  scroll: { flex: 1, backgroundColor: '#F7F8FB' },
  scrollContent: { flexGrow: 1 },
  shell: { flex: 1 },
  brandRow: {
    minHeight: 76,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
  },
  brandWordmark: { width: 168, height: 52 },
  closeButton: {
    width: layout.touchTarget,
    height: layout.touchTarget,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceSubtle,
  },
  identityCard: {
    minHeight: 104,
    marginHorizontal: 14,
    marginTop: 4,
    marginBottom: 14,
    padding: 17,
    borderRadius: 24,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    overflow: 'hidden',
    ...softShadow,
  },
  identityCopy: { flex: 1, minWidth: 0 },
  identityName: {
    color: colors.white,
    fontSize: 19,
    lineHeight: 24,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  identityEmail: {
    marginTop: 3,
    color: 'rgba(255,255,255,0.74)',
    fontSize: 12,
    lineHeight: 16,
    fontFamily: fontFamilies.regular,
    textAlign: 'right',
    writingDirection: 'ltr',
  },
  identitySubtitle: {
    marginTop: 3,
    color: 'rgba(255,255,255,0.74)',
    fontSize: 12,
    lineHeight: 17,
    fontFamily: fontFamilies.regular,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  guestIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  menuLabel: {
    marginHorizontal: 20,
    marginBottom: 7,
    color: colors.textLight,
    fontSize: 12,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  footer: { marginTop: 'auto', paddingHorizontal: 14, paddingTop: 20 },
  signOutButton: {
    minHeight: 48,
    borderRadius: 16,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FEECEC',
  },
  signOutText: {
    color: '#B42318',
    fontSize: 15,
    fontFamily: fontFamilies.semiBold,
    writingDirection: 'rtl',
  },
  version: {
    marginTop: 9,
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: fontFamilies.regular,
    textAlign: 'center',
  },
});

export const drawerMenuListStyles = StyleSheet.create({
  group: {
    marginHorizontal: 14,
    borderRadius: radii.lg,
    overflow: 'hidden',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.divider,
    ...softShadow,
  },
  row: {
    minHeight: 58,
    paddingHorizontal: 13,
    paddingVertical: 8,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#EDF0F4',
  },
  rowLast: { borderBottomWidth: 0 },
  iconBubble: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceSubtle,
  },
  label: {
    flex: 1,
    minWidth: 0,
    marginStart: 11,
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  badge: {
    minWidth: 22,
    height: 22,
    marginEnd: 7,
    paddingHorizontal: 6,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandOrange,
  },
  badgeText: {
    color: colors.white,
    fontSize: 10,
    fontFamily: fontFamilies.semiBold,
  },
  chevron: { marginStart: 2 },
});

export const settingsHubStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.appSurface },
  scroll: { flex: 1 },
  content: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    paddingHorizontal: 14,
    paddingTop: 17,
    paddingBottom: 48,
  },
  sectionTitle: {
    marginHorizontal: 7,
    marginBottom: 7,
    color: colors.textLight,
    fontSize: 12,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  group: {
    marginBottom: 16,
    borderRadius: radii.lg,
    overflow: 'hidden',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.divider,
    ...softShadow,
  },
  row: {
    minHeight: 60,
    paddingHorizontal: 13,
    paddingVertical: 9,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#EDF0F4',
  },
  rowLast: { borderBottomWidth: 0 },
  rowDisabled: { opacity: 0.58 },
  iconBubble: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceSubtle,
  },
  rowCopy: { flex: 1, minWidth: 0, marginStart: 11 },
  rowName: {
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  rowDetail: {
    marginTop: 2,
    color: colors.textLight,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: fontFamilies.regular,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  personalizationCard: {
    marginBottom: 16,
    padding: 15,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: '#F7D9A5',
    backgroundColor: '#FFF8EB',
  },
  personalizationTop: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: 11,
  },
  personalizationIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandOrange,
  },
  personalizationCopy: { flex: 1, minWidth: 0 },
  personalizationTitle: {
    color: colors.primary,
    fontSize: 16,
    lineHeight: 21,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  personalizationText: {
    marginTop: 4,
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fontFamilies.regular,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  resetButton: {
    alignSelf: 'flex-start',
    minHeight: layout.touchTarget,
    marginTop: 12,
    paddingHorizontal: 14,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#EFBD70',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    backgroundColor: colors.white,
  },
  resetText: {
    color: '#8A5507',
    fontSize: 13,
    fontFamily: fontFamilies.semiBold,
    writingDirection: 'rtl',
  },
  dangerGroup: { borderColor: '#F2CCCC' },
  dangerIcon: { backgroundColor: '#FEECEC' },
  dangerText: { color: '#B42318' },
  buttonDisabled: { opacity: 0.6 },
  modalOverlay: {
    flex: 1,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.48)',
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    padding: 20,
    borderRadius: 20,
    backgroundColor: colors.white,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontFamily: fontFamilies.semiBold,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  modalText: {
    marginTop: 8,
    color: colors.textSecondary,
    lineHeight: 20,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  modalInput: {
    height: 52,
    marginTop: 18,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    color: colors.textPrimary,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  modalActions: { marginTop: 18, flexDirection: 'row-reverse', gap: 10 },
  modalCancelButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
  },
  modalCancelText: { color: '#374151', fontFamily: fontFamilies.semiBold },
  modalDeleteButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#B42318',
  },
  modalDeleteText: { color: colors.white, fontFamily: fontFamilies.semiBold },
});

export const detailHeaderStyles = StyleSheet.create({
  backButton: {
    width: layout.touchTarget,
    height: layout.touchTarget,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceSubtle,
  },
});
